// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Zakupki.MosApi.V2
{
    public partial class MosSwaggerClientV2
    {
        public async Task<ProductionListDto?> ProductionSearchAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/production/public/Search");
            var queryString = FormatGetQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(queryString);
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ProductionListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<ProductionDirectoryListDto?> ProductiondirectorySearchAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/productionDirectory/public/Search");
            var queryString = FormatGetQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(queryString);
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ProductionDirectoryListDto>(stream, _serializerOptions, cancellationToken);
        }
    }
}
