// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Zakupki.MosApi.V2
{
    public partial class MosSwaggerClientV2
    {
        public async Task CommercialofferCreatecommercialofferrequestAsync(CreateCommercialOfferRequestCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/commercialOffer/commands/CreateCommercialOfferRequest");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task CommercialofferRevokecommercialofferrequestAsync(RevokeCommercialOfferRequestCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/commercialOffer/commands/RevokeCommercialOfferRequest");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task CommercialofferSendcommercialofferAsync(SendCommercialOfferCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/commercialOffer/commands/SendCommercialOffer");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }
    }
}
