// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Zakupki.MosApi.V2
{
    public partial class MosSwaggerClientV2
    {
        public async Task BankguaranteeApplyAsync(ApplyCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/bankGuarantee/commands/Apply");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task BankguaranteeIssueAsync(IssueCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/bankGuarantee/commands/Issue");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task BankguaranteeRejectAsync(RejectCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/bankGuarantee/commands/Reject");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task BankguaranteeRevisionrequiredAsync(RevisionRequiredCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/bankGuarantee/commands/RevisionRequired");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task BankguaranteeCancelAsync(CancelCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/bankGuarantee/externalCommands/Cancel");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task BankguaranteeRequestAsync(RequestCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/bankGuarantee/externalCommands/Request");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task BankguaranteeDownloadfileAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/bankGuarantee/queries/DownloadFile");
            var queryString = FormatGetQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(queryString);
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }
    }
}
