// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Zakupki.MosApi.V2
{
    public partial class MosSwaggerClientV2
    {
        public async Task NeedApproveneedsupplierstockrequestAsync(ApproveNeedSupplierStockRequestCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/need/public/ApproveNeedSupplierStockRequest");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task NeedRejectneedsupplierstockrequestAsync(RejectNeedSupplierStockRequestCommand? body, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/need/public/RejectNeedSupplierStockRequest");
            using var request = new HttpRequestMessage(new HttpMethod("POST"), urlBuilder.ToString());
            var json = JsonSerializer.Serialize(body, _serializerOptions);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            return;
        }

        public async Task<GetQueryDataDto2?> NeedGetAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/need/public/Get");
            var queryString = FormatGetQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(queryString);
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<GetQueryDataDto2>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SearchQueryListDto2?> NeedSearchAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v2/need/public/Search");
            var queryString = FormatGetQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(queryString);
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SearchQueryListDto2>(stream, _serializerOptions, cancellationToken);
        }
    }
}
