// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zakupki.Fetcher.Data;

#nullable disable

namespace Zakupki.Fetcher.Migrations
{
    [DbContext(typeof(NoticeDbContext))]
    [Migration("20251118090000_add_attachment_markdown")]
    partial class AddAttachmentMarkdown
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new SnapshotProxy().Build(modelBuilder);
        }

        private sealed class SnapshotProxy : NoticeDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder) => base.BuildModel(modelBuilder);
        }
    }
}
