// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zakupki.Fetcher.Data;

#nullable disable

namespace Zakupki.Fetcher.Migrations
{
    [DbContext(typeof(NoticeDbContext))]
    partial class NoticeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.AttachmentSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignatureType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.ToTable("AttachmentSignatures", (string)null);
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Period")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Article15FeaturesInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ContractConclusionOnSt83Ch2")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EtpCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EtpName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EtpUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Href")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Period")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlacingWayCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlacingWayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PurchaseObjectInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaxPriceCurrencyCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MaxPriceCurrencyName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Okpd2Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Okpd2Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("KvrCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("KvrName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SchemeVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Period")
                        .HasDatabaseName("IX_Notices_Period");

                    b.HasIndex("PurchaseNumber")
                        .HasDatabaseName("IX_Notices_PurchaseNumber");

                    b.ToTable("Notices", (string)null);
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.NoticeAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BinaryContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentKindCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocumentKindName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NoticeVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublishedContentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentKindCode")
                        .HasDatabaseName("IX_NoticeAttachments_DocKindCode");

                    b.HasIndex("FileName")
                        .HasDatabaseName("IX_NoticeAttachments_FileName");

                    b.HasIndex("NoticeVersionId");

                    b.HasIndex("PublishedContentId", "NoticeVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_NoticeAttachments_ContentId_Version");

                    b.ToTable("NoticeAttachments", (string)null);
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.NoticeSearchVector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmbeddingVector")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("NoticeVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NoticeVersionId")
                        .IsUnique();

                    b.ToTable("NoticeSearchVectors", (string)null);
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.NoticeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("VersionReceivedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("NoticeId");

                    b.HasIndex("ExternalId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_NoticeVersions_External_Version");

                    b.ToTable("NoticeVersions", (string)null);
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.ProcedureWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BiddingDateRaw")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("CollectingEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CollectingStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstPartsDateRaw")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("NoticeVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecondPartsDateRaw")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SubmissionProcedureDateRaw")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SummarizingDateRaw")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CollectingEnd")
                        .HasDatabaseName("IX_ProcedureWindows_CollectingEnd");

                    b.HasIndex("CollectingStart")
                        .HasDatabaseName("IX_ProcedureWindows_CollectingStart");

                    b.HasIndex("NoticeVersionId")
                        .IsUnique();

                    b.ToTable("ProcedureWindows", (string)null);
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.AttachmentSignature", b =>
                {
                    b.HasOne("Zakupki.Fetcher.Data.Entities.NoticeAttachment", "Attachment")
                        .WithMany("Signatures")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.NoticeAttachment", b =>
                {
                    b.HasOne("Zakupki.Fetcher.Data.Entities.NoticeVersion", "NoticeVersion")
                        .WithMany("Attachments")
                        .HasForeignKey("NoticeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeVersion");
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.NoticeSearchVector", b =>
                {
                    b.HasOne("Zakupki.Fetcher.Data.Entities.NoticeVersion", "NoticeVersion")
                        .WithOne("SearchVector")
                        .HasForeignKey("Zakupki.Fetcher.Data.Entities.NoticeSearchVector", "NoticeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeVersion");
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.NoticeVersion", b =>
                {
                    b.HasOne("Zakupki.Fetcher.Data.Entities.ImportBatch", "ImportBatch")
                        .WithMany("NoticeVersions")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zakupki.Fetcher.Data.Entities.Notice", "Notice")
                        .WithMany("Versions")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.ProcedureWindow", b =>
                {
                    b.HasOne("Zakupki.Fetcher.Data.Entities.NoticeVersion", "NoticeVersion")
                        .WithOne("ProcedureWindow")
                        .HasForeignKey("Zakupki.Fetcher.Data.Entities.ProcedureWindow", "NoticeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticeVersion");
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.ImportBatch", b =>
                {
                    b.Navigation("NoticeVersions");
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.Notice", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.NoticeAttachment", b =>
                {
                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("Zakupki.Fetcher.Data.Entities.NoticeVersion", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ProcedureWindow");

                    b.Navigation("SearchVector");
                });
#pragma warning restore 612, 618
        }
    }
}
