// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Zakupki.MosApi.V2
{
    public class ChangeWinnerCommand
    {
        [JsonPropertyName("auctionId")]
        public int? auctionId { get; set; }

        [JsonPropertyName("supplierPlace")]
        public int? supplierPlace { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class CreateSharedCommand
    {
        [JsonPropertyName("organizer")]
        public CustomerDto? organizer { get; set; }

        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("federalLaw")]
        public FederalLawEnum? federalLaw { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("type")]
        public CreateSharedTypeEnum? type { get; set; }

        [JsonPropertyName("duration")]
        public int? duration { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset? startDate { get; set; }

        [JsonPropertyName("items")]
        public List<SharedAuctionItemDto>? items { get; set; }

        [JsonPropertyName("stepPercent")]
        public double? stepPercent { get; set; }

        [JsonPropertyName("licenseRequest")]
        public LicenseRequestDto? licenseRequest { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ApproveAuctionSupplierStockRequestCommand
    {
        [JsonPropertyName("syncRequestId")]
        public string? syncRequestId { get; set; }

        [JsonPropertyName("stockCheckDate")]
        public DateTimeOffset stockCheckDate { get; set; } = default!;

        [JsonPropertyName("items")]
        public List<SupplierStockPurchaseItemDto>? items { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RejectAuctionSupplierStockRequestCommand
    {
        [JsonPropertyName("syncRequestId")]
        public string? syncRequestId { get; set; }

        [JsonPropertyName("stockCheckDate")]
        public DateTimeOffset stockCheckDate { get; set; } = default!;

        [JsonPropertyName("items")]
        public List<SupplierStockPurchaseItemDto>? items { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendChatMessageToEaistCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractId")]
        public int? contractId { get; set; }

        [JsonPropertyName("date")]
        public string? date { get; set; }

        [JsonPropertyName("chatId")]
        public string? chatId { get; set; }

        [JsonPropertyName("senderSystemUserId")]
        public int? senderSystemUserId { get; set; }

        [JsonPropertyName("chatMessageId")]
        public string? chatMessageId { get; set; }

        [JsonPropertyName("signedFileStorage")]
        public FileStorageDto? signedFileStorage { get; set; }
    }

    public class ProcessAsurCompanyRequestsCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ProcessAsurResponseQueueCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ApplyOrderPaymentCommand
    {
        [JsonPropertyName("paymentReceiptUrl")]
        public string? paymentReceiptUrl { get; set; }

        [JsonPropertyName("id")]
        public int id { get; set; } = default!;

        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ApplyOrderRequestCommand
    {
        [JsonPropertyName("paymentLink")]
        public string? paymentLink { get; set; }

        [JsonPropertyName("paymentLinkExpireDate")]
        public DateTimeOffset paymentLinkExpireDate { get; set; } = default!;

        [JsonPropertyName("id")]
        public int id { get; set; } = default!;

        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendAquireOrderRequestCommand
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;

        [JsonPropertyName("buyerCompanyId")]
        public int buyerCompanyId { get; set; } = default!;

        [JsonPropertyName("supplierCompanyAccount")]
        public CompanyBankAccountDto? supplierCompanyAccount { get; set; }

        [JsonPropertyName("totalSum")]
        public double? totalSum { get; set; }

        [JsonPropertyName("currency")]
        public CurrencyEnum? currency { get; set; }

        [JsonPropertyName("shippingAddress")]
        public string? shippingAddress { get; set; }

        [JsonPropertyName("successPaymentUrl")]
        public string? successPaymentUrl { get; set; }

        [JsonPropertyName("failedPaymentUrl")]
        public string? failedPaymentUrl { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RejectOrderPaymentCommand
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;

        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class CreateAuctionCommand
    {
        [JsonPropertyName("auctionId")]
        public int auctionId { get; set; } = default!;

        [JsonPropertyName("type")]
        public AuctionTypeEnum? type { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset startDate { get; set; } = default!;

        [JsonPropertyName("endDate")]
        public DateTimeOffset endDate { get; set; } = default!;

        [JsonPropertyName("customer")]
        public AuctionCustomerDto? customer { get; set; }

        [JsonPropertyName("federalLaw")]
        public FederalLawEnum? federalLaw { get; set; }

        [JsonPropertyName("conclusionReason")]
        public ConclusionReasonEnum? conclusionReason { get; set; }

        [JsonPropertyName("files")]
        public List<FileDto>? files { get; set; }

        [JsonPropertyName("externalUrl")]
        public string? externalUrl { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("items")]
        public List<AuctionItemDto>? items { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendAuctionSupplierWinCommand
    {
        [JsonPropertyName("auctionId")]
        public int auctionId { get; set; } = default!;

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ApplyCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("sum")]
        public double sum { get; set; } = default!;

        [JsonPropertyName("expirationDate")]
        public DateTimeOffset? expirationDate { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset? startDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("rate")]
        public double? rate { get; set; }

        [JsonPropertyName("commission")]
        public double? commission { get; set; }

        [JsonPropertyName("contractFile")]
        public FileDto? contractFile { get; set; }

        [JsonPropertyName("bankGuaranteeFile")]
        public FileDto? bankGuaranteeFile { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("externalUrl")]
        public string? externalUrl { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class CancelCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RequestCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("type")]
        public BankGuaranteeTypeEnum? type { get; set; }

        [JsonPropertyName("sum")]
        public double sum { get; set; } = default!;

        [JsonPropertyName("beginDate")]
        public DateTimeOffset beginDate { get; set; } = default!;

        [JsonPropertyName("endDate")]
        public DateTimeOffset endDate { get; set; } = default!;

        [JsonPropertyName("supplierInfo")]
        public SupplierDto? supplierInfo { get; set; }

        [JsonPropertyName("customerInfo")]
        public CompanyDto? customerInfo { get; set; }

        [JsonPropertyName("subject")]
        public SubjectDto? subject { get; set; }

        [JsonPropertyName("files")]
        public List<RequestFileDto>? files { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class IssueCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("date")]
        public DateTimeOffset date { get; set; } = default!;

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RejectCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("errors")]
        public Dictionary<string, object>? errors { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RevisionRequiredCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("errors")]
        public Dictionary<string, object>? errors { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ChangeUpdStatusCommand
    {
        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("executionStatus")]
        public ExecutionStatusDto? executionStatus { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractConcludedActionCommand
    {
        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("contractExternalId")]
        public string? contractExternalId { get; set; }

        [JsonPropertyName("registerNumber")]
        public string? registerNumber { get; set; }

        [JsonPropertyName("conclusionDate")]
        public DateTimeOffset conclusionDate { get; set; } = default!;

        [JsonPropertyName("signedFiles")]
        public List<FileSignatureDto3>? signedFiles { get; set; }

        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractProjectActionCommand
    {
        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("responseDateRequired")]
        public DateTimeOffset responseDateRequired { get; set; } = default!;

        [JsonPropertyName("contract")]
        public ContractProjectDto? contract { get; set; }

        [JsonPropertyName("filesForSigning")]
        public List<FileDto>? filesForSigning { get; set; }

        [JsonPropertyName("additionalFiles")]
        public List<ContractPojectActionAdditionalFileDto>? additionalFiles { get; set; }

        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractRejectConclusionActionCommand
    {
        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("contractExternalId")]
        public string? contractExternalId { get; set; }

        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractSupplementaryAgreementProjectActionCommand
    {
        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("responseDateRequired")]
        public DateTimeOffset responseDateRequired { get; set; } = default!;

        [JsonPropertyName("supplementaryAgreement")]
        public ContractProjectDto? supplementaryAgreement { get; set; }

        [JsonPropertyName("filesForSigning")]
        public List<FileDto>? filesForSigning { get; set; }

        [JsonPropertyName("additionalFiles")]
        public List<ContractSupplementaryAgreementAdditionalFileDto>? additionalFiles { get; set; }

        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractWithdrawActionCommand
    {
        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("contractExternalId")]
        public string? contractExternalId { get; set; }

        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractDisagreementProtocolActionCommand
    {
        [JsonPropertyName("responseDateRequired")]
        public DateTimeOffset responseDateRequired { get; set; } = default!;

        [JsonPropertyName("contractId")]
        public int contractId { get; set; } = default!;

        [JsonPropertyName("contractExternalId")]
        public string? contractExternalId { get; set; }

        [JsonPropertyName("disagreementProtocolFile")]
        public FileSignatureDto3? disagreementProtocolFile { get; set; }

        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractRejectConclusionActionCommand2
    {
        [JsonPropertyName("contractExternalId")]
        public string? contractExternalId { get; set; }

        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractSignedBySupplierActionCommand
    {
        [JsonPropertyName("responseDateRequired")]
        public DateTimeOffset responseDateRequired { get; set; } = default!;

        [JsonPropertyName("contractExternalId")]
        public string? contractExternalId { get; set; }

        [JsonPropertyName("projectSignedFile")]
        public List<FileSignatureDto3>? projectSignedFile { get; set; }

        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ContractNotificationCommand
    {
        [JsonPropertyName("esiaId")]
        public string? esiaId { get; set; }

        [JsonPropertyName("type")]
        public ContractNotificationTypeEnum? type { get; set; }

        [JsonPropertyName("contractId")]
        public string? contractId { get; set; }

        [JsonPropertyName("offerId")]
        public int offerId { get; set; } = default!;

        [JsonPropertyName("url")]
        public string? url { get; set; }

        [JsonPropertyName("message")]
        public string? message { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendSupplierCatalogCommand
    {
        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("kpp")]
        public string? kpp { get; set; }

        [JsonPropertyName("esiaId")]
        public string? esiaId { get; set; }

        [JsonPropertyName("offerIds")]
        public List<int>? offerIds { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class OfferNotificationCommand
    {
        [JsonPropertyName("esiaId")]
        public string? esiaId { get; set; }

        [JsonPropertyName("type")]
        public OfferChangedTypeEnum? type { get; set; }

        [JsonPropertyName("proposalId")]
        public string? proposalId { get; set; }

        [JsonPropertyName("message")]
        public string? message { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendEetpResultCommand
    {
        [JsonPropertyName("hasErrors")]
        public bool hasErrors { get; set; } = default!;

        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("kpp")]
        public string? kpp { get; set; }

        [JsonPropertyName("esiaId")]
        public string? esiaId { get; set; }

        [JsonPropertyName("results")]
        public List<PublishResult>? results { get; set; }

        [JsonPropertyName("proposalId")]
        public string? proposalId { get; set; }

        [JsonPropertyName("url")]
        public string? url { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendProcedureWinnerCommand
    {
        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("kpp")]
        public string? kpp { get; set; }

        [JsonPropertyName("esiaId")]
        public string? esiaId { get; set; }

        [JsonPropertyName("winnersInfo")]
        public List<ProcedureWinnerInfo>? winnersInfo { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ApplyRequestCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("sum")]
        public double sum { get; set; } = default!;

        [JsonPropertyName("expirationDate")]
        public DateTimeOffset? expirationDate { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset? startDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("factoringPeriod")]
        public int factoringPeriod { get; set; } = default!;

        [JsonPropertyName("amountPayment")]
        public int amountPayment { get; set; } = default!;

        [JsonPropertyName("commission")]
        public double? commission { get; set; }

        [JsonPropertyName("contractFile")]
        public FileDto? contractFile { get; set; }

        [JsonPropertyName("factoringFile")]
        public FileDto? factoringFile { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("externalUrl")]
        public string? externalUrl { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RequestCommand2
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("type")]
        public FactoringTypeEnum? type { get; set; }

        [JsonPropertyName("view")]
        public FactoringViewEnum? view { get; set; }

        [JsonPropertyName("sum")]
        public double sum { get; set; } = default!;

        [JsonPropertyName("amountPayment")]
        public double amountPayment { get; set; } = default!;

        [JsonPropertyName("deferredPaymentPeriod")]
        public int deferredPaymentPeriod { get; set; } = default!;

        [JsonPropertyName("additionalPaymentPeriod")]
        public int additionalPaymentPeriod { get; set; } = default!;

        [JsonPropertyName("startDate")]
        public DateTimeOffset? startDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("expectedDate")]
        public DateTimeOffset? expectedDate { get; set; }

        [JsonPropertyName("supplierInfo")]
        public SupplierDto2? supplierInfo { get; set; }

        [JsonPropertyName("customerInfo")]
        public CompanyDto? customerInfo { get; set; }

        [JsonPropertyName("subject")]
        public SubjectDto? subject { get; set; }

        [JsonPropertyName("files")]
        public List<RequestFileDto>? files { get; set; }

        [JsonPropertyName("applicantPosition")]
        public string? applicantPosition { get; set; }

        [JsonPropertyName("supplierPostalAddress")]
        public string? supplierPostalAddress { get; set; }

        [JsonPropertyName("applicantPerson")]
        public PersonDto? applicantPerson { get; set; }

        [JsonPropertyName("supplierComment")]
        public string? supplierComment { get; set; }

        [JsonPropertyName("supplierContactPhone")]
        public string? supplierContactPhone { get; set; }

        [JsonPropertyName("supplierContactEmail")]
        public string? supplierContactEmail { get; set; }

        [JsonPropertyName("supplierContactName")]
        public string? supplierContactName { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RejectRequestCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("errors")]
        public Dictionary<string, object>? errors { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ApplyOrderCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("sum")]
        public double sum { get; set; } = default!;

        [JsonPropertyName("insurancePremium")]
        public double insurancePremium { get; set; } = default!;

        [JsonPropertyName("franchise")]
        public double? franchise { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset? startDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("contractFile")]
        public FileDto? contractFile { get; set; }

        [JsonPropertyName("insuranceFile")]
        public FileDto? insuranceFile { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("externalUrl")]
        public string? externalUrl { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RequestCommand3
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("type")]
        public InsuranceTypeEnum? type { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset? startDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("beginPrice")]
        public double? beginPrice { get; set; }

        [JsonPropertyName("withFranchise")]
        public bool? withFranchise { get; set; }

        [JsonPropertyName("supplierInfo")]
        public SupplierDto2? supplierInfo { get; set; }

        [JsonPropertyName("customerInfo")]
        public CompanyDto? customerInfo { get; set; }

        [JsonPropertyName("subject")]
        public SubjectDto? subject { get; set; }

        [JsonPropertyName("files")]
        public List<RequestFileDto>? files { get; set; }

        [JsonPropertyName("insuranceCases")]
        public List<InsuranceCaseEnum>? insuranceCases { get; set; }

        [JsonPropertyName("insuranceObjectName")]
        public string? insuranceObjectName { get; set; }

        [JsonPropertyName("insuranceObjectAddress")]
        public string? insuranceObjectAddress { get; set; }

        [JsonPropertyName("insuranceObjectFloorCount")]
        public int? insuranceObjectFloorCount { get; set; }

        [JsonPropertyName("insurancePurposeEnumId")]
        public InsurancePurposeEnum? insurancePurposeEnumId { get; set; }

        [JsonPropertyName("insuranceObjectConstructionYear")]
        public int? insuranceObjectConstructionYear { get; set; }

        [JsonPropertyName("insuranceObjectLastRepairYear")]
        public int? insuranceObjectLastRepairYear { get; set; }

        [JsonPropertyName("insuranceBuildingEnumId")]
        public InsuranceBuildingEnum? insuranceBuildingEnumId { get; set; }

        [JsonPropertyName("insuranceTypeWorkEnumId")]
        public List<InsuranceTypeWorkEnum>? insuranceTypeWorkEnumId { get; set; }

        [JsonPropertyName("insuranceObjectItems")]
        public List<InsuranceObjectItemEnum>? insuranceObjectItems { get; set; }

        [JsonPropertyName("applicantPosition")]
        public string? applicantPosition { get; set; }

        [JsonPropertyName("supplierPostalAddress")]
        public string? supplierPostalAddress { get; set; }

        [JsonPropertyName("applicantPerson")]
        public PersonDto? applicantPerson { get; set; }

        [JsonPropertyName("supplierComment")]
        public string? supplierComment { get; set; }

        [JsonPropertyName("supplierContactPhone")]
        public string? supplierContactPhone { get; set; }

        [JsonPropertyName("supplierContactEmail")]
        public string? supplierContactEmail { get; set; }

        [JsonPropertyName("supplierContactName")]
        public string? supplierContactName { get; set; }

        [JsonPropertyName("supplierTaxationType")]
        public TaxationTypeEnum? supplierTaxationType { get; set; }

        [JsonPropertyName("areaActivity")]
        public string? areaActivity { get; set; }

        [JsonPropertyName("experienceActivity")]
        public string? experienceActivity { get; set; }

        [JsonPropertyName("previousInsuranceCompany")]
        public string? previousInsuranceCompany { get; set; }

        [JsonPropertyName("previousAgreementNumber")]
        public string? previousAgreementNumber { get; set; }

        [JsonPropertyName("previousSum")]
        public double? previousSum { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RejectOrderCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("errors")]
        public Dictionary<string, object>? errors { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendNeedSupplierWinCommand
    {
        [JsonPropertyName("needId")]
        public int needId { get; set; } = default!;

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class UploadNeedProposalProtocolCommand
    {
        [JsonPropertyName("needId")]
        public int? needId { get; set; }

        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("supplierPropositions")]
        public List<NeedSupplierPropositionDto>? supplierPropositions { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class AuctionSupplierStockSyncCommand
    {
        [JsonPropertyName("auctionId")]
        public int auctionId { get; set; } = default!;

        [JsonPropertyName("syncRequestId")]
        public string? syncRequestId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class NeedSupplierStockSyncCommand
    {
        [JsonPropertyName("needId")]
        public int needId { get; set; } = default!;

        [JsonPropertyName("syncRequestId")]
        public string? syncRequestId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class CreateCommercialOfferRequestCommand
    {
        [JsonPropertyName("commercialOfferRequest")]
        public CommercialOfferRequestDto? commercialOfferRequest { get; set; }

        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RevokeCommercialOfferRequestCommand
    {
        [JsonPropertyName("revokeRequest")]
        public CustomerRevokeCommercialOfferRequestDto? revokeRequest { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendCommercialOfferCommand
    {
        [JsonPropertyName("commercialOffer")]
        public SendCommercialOfferCommandInfo? commercialOffer { get; set; }

        [JsonPropertyName("externalSystemCode")]
        public ExternalSystemEnum2? externalSystemCode { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SendCommercialOfferCommandInfo
    {
        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("supplier")]
        public CommercialOfferSupplierDto? supplier { get; set; }

        [JsonPropertyName("type")]
        public bool? type { get; set; }

        [JsonPropertyName("proposalDate")]
        public DateTimeOffset? proposalDate { get; set; }

        [JsonPropertyName("expirationDate")]
        public DateTimeOffset? expirationDate { get; set; }

        [JsonPropertyName("offerDocLink")]
        public string? offerDocLink { get; set; }

        [JsonPropertyName("offerDocName")]
        public string? offerDocName { get; set; }

        [JsonPropertyName("specItems")]
        public List<CommercialOfferItemDto>? specItems { get; set; }

        [JsonPropertyName("expenses")]
        public CommercialOfferExpenseDto? expenses { get; set; }

        [JsonPropertyName("sum")]
        public double? sum { get; set; }
    }

    public class DeleteCommand
    {
        [JsonPropertyName("entityId")]
        public string? entityId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ImportCommand
    {
        [JsonPropertyName("importData")]
        public string? importData { get; set; }

        [JsonPropertyName("contractId")]
        public int contractId { get; set; } = default!;

        [JsonPropertyName("deliveryId")]
        public int deliveryId { get; set; } = default!;

        [JsonPropertyName("stageId")]
        public int stageId { get; set; } = default!;

        [JsonPropertyName("executionId")]
        public string? executionId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class CheckSendPackageToEisCommand
    {
        [JsonPropertyName("fileId")]
        public string? fileId { get; set; }

        [JsonPropertyName("packetId")]
        public string? packetId { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class DownloadPacketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("documentKind")]
        public EdoDocumentKindEnum? documentKind { get; set; }

        [JsonPropertyName("documentUid")]
        public string? documentUid { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("document")]
        public string? document { get; set; }

        [JsonPropertyName("documentSignatures")]
        public List<string>? documentSignatures { get; set; }

        [JsonPropertyName("applicationId")]
        public string? applicationId { get; set; }

        [JsonPropertyName("application")]
        public string? application { get; set; }

        [JsonPropertyName("applicationSignatures")]
        public List<string>? applicationSignatures { get; set; }
    }

    public class FindAndQueueUnprocessedActualPacketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }
    }

    public class FindAndQueueUnprocessedTicketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }
    }

    public class GenerateUkdCorrFilesForEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUkdCorrSameFilesForEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUkdFilesForEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUkdSameFilesForEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUpdCorrFilesForEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUpdCorrSameFilesForEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUpdFilesForConstructionEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUpdFilesForEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUpdSameFilesForEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class ContractExecutionEisSignResultCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("originHeaderValue")]
        public string? originHeaderValue { get; set; }

        [JsonPropertyName("uid")]
        public string? uid { get; set; }

        [JsonPropertyName("signResult")]
        public EisSignResultDto? signResult { get; set; }
    }

    public class CheckSendToDiadocCommand
    {
        [JsonPropertyName("recipientBoxId")]
        public string? recipientBoxId { get; set; }

        [JsonPropertyName("messageId")]
        public string? messageId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class DownloadDiadocPrintFormCommand
    {
        [JsonPropertyName("messageId")]
        public string? messageId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateDiadocFnsFileCommand
    {
        [JsonPropertyName("recipienCompanytId")]
        public int? recipienCompanytId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("fileType")]
        public FileTypeEnum? fileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class SendFnsFileToDiadocCommand
    {
        [JsonPropertyName("senderId")]
        public string? senderId { get; set; }

        [JsonPropertyName("recipientId")]
        public string? recipientId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("fileType")]
        public FileTypeEnum? fileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateUpdSameFilesForConstructionEisCommand
    {
        [JsonPropertyName("senderCompanyId")]
        public int? senderCompanyId { get; set; }

        [JsonPropertyName("recipientCompanyId")]
        public int? recipientCompanyId { get; set; }

        [JsonPropertyName("docFileId")]
        public int? docFileId { get; set; }

        [JsonPropertyName("moscowPdfFileType")]
        public FileTypeEnum? moscowPdfFileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class GenerateKalugaFnsFileCommand
    {
        [JsonPropertyName("recipienCompanytId")]
        public int? recipienCompanytId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("fileType")]
        public FileTypeEnum? fileType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class SendExecutionFilesToKalugaCommand
    {
        [JsonPropertyName("senderId")]
        public string? senderId { get; set; }

        [JsonPropertyName("recipientId")]
        public string? recipientId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("fileType")]
        public FileTypeEnum? fileType { get; set; }

        [JsonPropertyName("mrpaExternalId")]
        public string? mrpaExternalId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class ProcessActBuyerTicketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("documentKind")]
        public EdoDocumentKindEnum? documentKind { get; set; }

        [JsonPropertyName("documentUid")]
        public string? documentUid { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("document")]
        public string? document { get; set; }

        [JsonPropertyName("documentSignatures")]
        public List<string>? documentSignatures { get; set; }

        [JsonPropertyName("applicationId")]
        public string? applicationId { get; set; }

        [JsonPropertyName("application")]
        public string? application { get; set; }

        [JsonPropertyName("applicationSignatures")]
        public List<string>? applicationSignatures { get; set; }
    }

    public class ProcessActSupplierTicketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("documentKind")]
        public EdoDocumentKindEnum? documentKind { get; set; }

        [JsonPropertyName("documentUid")]
        public string? documentUid { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("document")]
        public string? document { get; set; }

        [JsonPropertyName("documentSignatures")]
        public List<string>? documentSignatures { get; set; }

        [JsonPropertyName("applicationId")]
        public string? applicationId { get; set; }

        [JsonPropertyName("application")]
        public string? application { get; set; }

        [JsonPropertyName("applicationSignatures")]
        public List<string>? applicationSignatures { get; set; }
    }

    public class ProcessUkdBuyerTicketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("documentKind")]
        public EdoDocumentKindEnum? documentKind { get; set; }

        [JsonPropertyName("documentUid")]
        public string? documentUid { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("document")]
        public string? document { get; set; }

        [JsonPropertyName("documentSignatures")]
        public List<string>? documentSignatures { get; set; }

        [JsonPropertyName("applicationId")]
        public string? applicationId { get; set; }

        [JsonPropertyName("application")]
        public string? application { get; set; }

        [JsonPropertyName("applicationSignatures")]
        public List<string>? applicationSignatures { get; set; }
    }

    public class ProcessUpdSupplierTicketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("documentKind")]
        public EdoDocumentKindEnum? documentKind { get; set; }

        [JsonPropertyName("documentUid")]
        public string? documentUid { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("document")]
        public string? document { get; set; }

        [JsonPropertyName("documentSignatures")]
        public List<string>? documentSignatures { get; set; }

        [JsonPropertyName("applicationId")]
        public string? applicationId { get; set; }

        [JsonPropertyName("application")]
        public string? application { get; set; }

        [JsonPropertyName("applicationSignatures")]
        public List<string>? applicationSignatures { get; set; }
    }

    public class PeekTicketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("documentKind")]
        public EdoDocumentKindEnum? documentKind { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }
    }

    public class ProcessEisSignResultCommand
    {
        [JsonPropertyName("signSuccess")]
        public bool? signSuccess { get; set; }

        [JsonPropertyName("signErrors")]
        public List<string>? signErrors { get; set; }

        [JsonPropertyName("signQueueIndexId")]
        public string? signQueueIndexId { get; set; }

        [JsonPropertyName("signQueueRefId")]
        public string? signQueueRefId { get; set; }

        [JsonPropertyName("documentType")]
        public string? documentType { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("contractRegisterNumber")]
        public string? contractRegisterNumber { get; set; }

        [JsonPropertyName("isSupplierTicketDocumentType")]
        public bool? isSupplierTicketDocumentType { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class ProcessUpdBuyerTicketFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("documentKind")]
        public EdoDocumentKindEnum? documentKind { get; set; }

        [JsonPropertyName("documentUid")]
        public string? documentUid { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("document")]
        public string? document { get; set; }

        [JsonPropertyName("documentSignatures")]
        public List<string>? documentSignatures { get; set; }

        [JsonPropertyName("applicationId")]
        public string? applicationId { get; set; }

        [JsonPropertyName("application")]
        public string? application { get; set; }

        [JsonPropertyName("applicationSignatures")]
        public List<string>? applicationSignatures { get; set; }
    }

    public class ProcessUpdUkdBuyerUvUtochFromEisLkpCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("documentKind")]
        public EdoDocumentKindEnum? documentKind { get; set; }

        [JsonPropertyName("documentUid")]
        public string? documentUid { get; set; }

        [JsonPropertyName("docEisId")]
        public string? docEisId { get; set; }

        [JsonPropertyName("documentId")]
        public string? documentId { get; set; }

        [JsonPropertyName("document")]
        public string? document { get; set; }

        [JsonPropertyName("documentSignatures")]
        public List<string>? documentSignatures { get; set; }

        [JsonPropertyName("applicationId")]
        public string? applicationId { get; set; }

        [JsonPropertyName("application")]
        public string? application { get; set; }

        [JsonPropertyName("applicationSignatures")]
        public List<string>? applicationSignatures { get; set; }
    }

    public class SendPackageToEisCommand
    {
        [JsonPropertyName("senderId")]
        public string? senderId { get; set; }

        [JsonPropertyName("recipientId")]
        public string? recipientId { get; set; }

        [JsonPropertyName("packageAttachmentType")]
        public PackageAttachmentType? packageAttachmentType { get; set; }

        [JsonPropertyName("fnsFileId")]
        public int? fnsFileId { get; set; }

        [JsonPropertyName("eisFileId")]
        public int? eisFileId { get; set; }

        [JsonPropertyName("attachmentFileIds")]
        public List<int>? attachmentFileIds { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("contractExecutionEntityId")]
        public string? contractExecutionEntityId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("contractSupplierCompanyId")]
        public int? contractSupplierCompanyId { get; set; }
    }

    public class SyncWithEisCommand
    {
        [JsonPropertyName("execution")]
        public NewContractExecutionEisSyncDto? execution { get; set; }

        [JsonPropertyName("documentsToProcess")]
        public List<EisDocumentDto>? documentsToProcess { get; set; }

        [JsonPropertyName("contractEntityId")]
        public int? contractEntityId { get; set; }

        [JsonPropertyName("contractRegisterNumber")]
        public string? contractRegisterNumber { get; set; }

        [JsonPropertyName("userToken")]
        public string? userToken { get; set; }

        [JsonPropertyName("objectId")]
        public string? objectId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("sourceOperationId")]
        public string? sourceOperationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("ppIdentity")]
        public PpIdentity? ppIdentity { get; set; }

        [JsonPropertyName("jobId")]
        public int? jobId { get; set; }

        [JsonPropertyName("parentJobId")]
        public int? parentJobId { get; set; }
    }

    public class ExecutedCommand
    {
        [JsonPropertyName("files")]
        public List<FileSignatureDto2>? files { get; set; }

        [JsonPropertyName("contractExternalId")]
        public string? contractExternalId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class SyncExecutionsWithEisCommand
    {
        [JsonPropertyName("contractEntityId")]
        public int? contractEntityId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("ppIdentity")]
        public PpIdentity? ppIdentity { get; set; }

        [JsonPropertyName("jobId")]
        public int? jobId { get; set; }
    }

    public class TerminationAgreementProjectCommand
    {
        [JsonPropertyName("previousOperationId")]
        public string? previousOperationId { get; set; }

        [JsonPropertyName("responseDateRequired")]
        public DateTimeOffset responseDateRequired { get; set; } = default!;

        [JsonPropertyName("filesForSigning")]
        public List<FileDto>? filesForSigning { get; set; }

        [JsonPropertyName("additionalFiles")]
        public List<SupplementaryAgreementAdditionalFileDto>? additionalFiles { get; set; }

        [JsonPropertyName("contractExternalId")]
        public string? contractExternalId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("actionDate")]
        public DateTimeOffset actionDate { get; set; } = default!;

        [JsonPropertyName("executor")]
        public string? executor { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class OrderStatusChangedCommand
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("event")]
        public string? @event { get; set; }

        [JsonPropertyName("time")]
        public string? time { get; set; }

        [JsonPropertyName("data")]
        public CommandData? data { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class CommandData
    {
        [JsonPropertyName("id")]
        public int? id { get; set; }

        [JsonPropertyName("status")]
        public string? status { get; set; }

        [JsonPropertyName("statusAt")]
        public string? statusAt { get; set; }

        [JsonPropertyName("createdAt")]
        public string? createdAt { get; set; }

        [JsonPropertyName("reviewer")]
        public object? reviewer { get; set; }

        [JsonPropertyName("events")]
        public List<object>? events { get; set; }

        [JsonPropertyName("order")]
        public CommandOrder? order { get; set; }
    }

    public class CommandOrder
    {
        [JsonPropertyName("id")]
        public int? id { get; set; }

        [JsonPropertyName("status")]
        public string? status { get; set; }

        [JsonPropertyName("statusAt")]
        public string? statusAt { get; set; }

        [JsonPropertyName("createdAt")]
        public string? createdAt { get; set; }

        [JsonPropertyName("applicant")]
        public object? applicant { get; set; }

        [JsonPropertyName("service")]
        public CommandOrderService? service { get; set; }

        [JsonPropertyName("customers")]
        public List<object>? customers { get; set; }
    }

    public class CommandOrderService
    {
        [JsonPropertyName("service_type")]
        public string? service_type { get; set; }
    }

    public class SyncKnowledgeBaseArticlesInboundCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }
    }

    public class CreateLogisticsOrderCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("ppIdentity")]
        public PpIdentity? ppIdentity { get; set; }

        [JsonPropertyName("logisticsOrderEntityId")]
        public string? logisticsOrderEntityId { get; set; }
    }

    public class ProcessLogisticsOrderChangesCommand
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }

        [JsonPropertyName("changes")]
        public LogisticsOrderDto2? changes { get; set; }
    }

    public class CreateSharedCommand2
    {
        [JsonPropertyName("customer")]
        public CustomerDto2? customer { get; set; }

        [JsonPropertyName("organizer")]
        public CustomerDto2? organizer { get; set; }

        [JsonPropertyName("items")]
        public List<SharedNeedItemDto>? items { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("nmck")]
        public double? nmck { get; set; }

        [JsonPropertyName("isIndefiniteVolume")]
        public bool? isIndefiniteVolume { get; set; }

        [JsonPropertyName("ikz")]
        public string? ikz { get; set; }

        [JsonPropertyName("proposalStartDate")]
        public DateTimeOffset? proposalStartDate { get; set; }

        [JsonPropertyName("proposalEndDate")]
        public DateTimeOffset? proposalEndDate { get; set; }

        [JsonPropertyName("planContractDate")]
        public DateTimeOffset? planContractDate { get; set; }

        [JsonPropertyName("files")]
        public List<ExternalFileDto>? files { get; set; }

        [JsonPropertyName("externalUrl")]
        public string? externalUrl { get; set; }

        [JsonPropertyName("federalLaw")]
        public FederalLawEnum? federalLaw { get; set; }

        [JsonPropertyName("conclusionReason")]
        public ConclusionReasonEnum? conclusionReason { get; set; }

        [JsonPropertyName("number")]
        public string? number { get; set; }

        [JsonPropertyName("isB2B")]
        public bool? isB2B { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ApproveNeedSupplierStockRequestCommand
    {
        [JsonPropertyName("syncRequestId")]
        public string? syncRequestId { get; set; }

        [JsonPropertyName("stockCheckDate")]
        public DateTimeOffset stockCheckDate { get; set; } = default!;

        [JsonPropertyName("items")]
        public List<SupplierStockPurchaseItemDto>? items { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class RejectNeedSupplierStockRequestCommand
    {
        [JsonPropertyName("syncRequestId")]
        public string? syncRequestId { get; set; }

        [JsonPropertyName("stockCheckDate")]
        public DateTimeOffset stockCheckDate { get; set; } = default!;

        [JsonPropertyName("items")]
        public List<SupplierStockPurchaseItemDto>? items { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class UploadCommand
    {
        [JsonPropertyName("file")]
        public ExternalFileDto? file { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class StatusChangedCommand
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;

        [JsonPropertyName("skuId")]
        public int skuId { get; set; } = default!;

        [JsonPropertyName("number")]
        public string? number { get; set; }

        [JsonPropertyName("url")]
        public string? url { get; set; }

        [JsonPropertyName("status")]
        public SkuChangeRequestStatusEnum? status { get; set; }

        [JsonPropertyName("user")]
        public UserInfoDto? user { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class AddExternalIntegrationQueueCommand
    {
        [JsonPropertyName("body")]
        public string? body { get; set; }

        [JsonPropertyName("externalSystemUserId")]
        public int externalSystemUserId { get; set; } = default!;

        [JsonPropertyName("packageType")]
        public string? packageType { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("diagnosticsActivityId")]
        public string? diagnosticsActivityId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class OperationCompleteCommand
    {
        [JsonPropertyName("hasErrors")]
        public bool? hasErrors { get; set; }

        [JsonPropertyName("errors")]
        public Dictionary<string, object>? errors { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class OperationCompleteCommand2
    {
        [JsonPropertyName("hasErrors")]
        public bool? hasErrors { get; set; }

        [JsonPropertyName("errors")]
        public Dictionary<string, object>? errors { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }

    public class ProcessIntegrationQueueCommand
    {
        [JsonPropertyName("packageId")]
        public string? packageId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }
}
