// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Zakupki.MosApi.V2
{
    public class SearchFinishedQueryListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<SearchFinishedQueryListDto2>? items { get; set; }
    }

    public class SearchQueryListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<SearchQueryListDto3>? items { get; set; }
    }

    public class ContractExecutionQueryListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<ContractExecutionQueryListDto2>? items { get; set; }
    }

    public class ContractListQueryDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<ContractListQueryDto2>? items { get; set; }
    }

    public class MedicationsContractListQueryDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<MedicationsContractListQueryDto2>? items { get; set; }
    }

    public class SearchQueryListDto2
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<SearchQueryListDto4>? items { get; set; }
    }

    public class SearchFinishedQuery
    {
        [JsonPropertyName("filter")]
        public SearchFinishedQueryFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SearchFinishedQueryCompanyDto
    {
        [JsonPropertyName("items")]
        public List<SearchFinishedQuerySpecificationDto>? items { get; set; }

        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class SearchFinishedQueryFilterDto
    {
        [JsonPropertyName("endDate")]
        public DateTime2? endDate { get; set; }

        [JsonPropertyName("supplierInn")]
        public String2? supplierInn { get; set; }

        [JsonPropertyName("supplierOgrn")]
        public String2? supplierOgrn { get; set; }
    }

    public class SearchFinishedQueryListDto2
    {
        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("federalLaw")]
        public FederalLawEnum? federalLaw { get; set; }

        [JsonPropertyName("conclusionReason")]
        public ConclusionReasonEnum? conclusionReason { get; set; }

        [JsonPropertyName("startPrice")]
        public double? startPrice { get; set; }

        [JsonPropertyName("contractCost")]
        public double? contractCost { get; set; }

        [JsonPropertyName("beginDate")]
        public DateTimeOffset? beginDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("customers")]
        public List<SearchFinishedQueryCompanyDto>? customers { get; set; }

        [JsonPropertyName("url")]
        public string? url { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class SearchFinishedQuerySpecificationDto
    {
        [JsonPropertyName("okpd2")]
        public string? okpd2 { get; set; }

        [JsonPropertyName("amount")]
        public double? amount { get; set; }

        [JsonPropertyName("url")]
        public string? url { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class DownloadFileQuery
    {
        [JsonPropertyName("fileId")]
        public int? fileId { get; set; }
    }

    public class GetQuery
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;
    }

    public class GetQueryDataDeliveryDto
    {
        [JsonPropertyName("daysEnd")]
        public int? daysEnd { get; set; }

        [JsonPropertyName("daysStart")]
        public int? daysStart { get; set; }

        [JsonPropertyName("address")]
        public string? address { get; set; }

        [JsonPropertyName("details")]
        public string? details { get; set; }

        [JsonPropertyName("startDate")]
        public DateTimeOffset? startDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("quantity")]
        public double? quantity { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public partial class GetQueryDataDto
    {
        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("status")]
        public StatusEnum3? status { get; set; }

        [JsonPropertyName("company")]
        public SearchQueryCompanyDto? company { get; set; }

        [JsonPropertyName("federalLaw")]
        public FederalLawEnum? federalLaw { get; set; }

        [JsonPropertyName("conclusionReason")]
        public ConclusionReasonEnum? conclusionReason { get; set; }

        [JsonPropertyName("startPrice")]
        public double? startPrice { get; set; }

        [JsonPropertyName("beginDate")]
        public DateTimeOffset? beginDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("isElectronicContractExecutionRequired")]
        public bool? isElectronicContractExecutionRequired { get; set; }

        [JsonPropertyName("isQuantityUnknown")]
        public bool? isQuantityUnknown { get; set; }

        [JsonPropertyName("items")]
        public List<GetQueryDataItemDto>? items { get; set; }

        [JsonPropertyName("regionId")]
        public int? regionId { get; set; }

        [JsonPropertyName("winner")]
        public SearchQueryCompanyDto? winner { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class GetQueryDataItemDto
    {
        [JsonPropertyName("oksmCode")]
        public string? oksmCode { get; set; }

        [JsonPropertyName("okeiCode")]
        public string? okeiCode { get; set; }

        [JsonPropertyName("kpgzCode")]
        public string? kpgzCode { get; set; }

        [JsonPropertyName("okpdCode")]
        public string? okpdCode { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("deliveries")]
        public List<GetQueryDataDeliveryDto>? deliveries { get; set; }

        [JsonPropertyName("quantity")]
        public double? quantity { get; set; }

        [JsonPropertyName("costPerUnit")]
        public double? costPerUnit { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class SearchQuery
    {
        [JsonPropertyName("filter")]
        public SearchQueryFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SearchQueryFilterDto
    {
        [JsonPropertyName("status")]
        public StatusEnum? status { get; set; }

        [JsonPropertyName("customerInn")]
        public String2? customerInn { get; set; }

        [JsonPropertyName("customerName")]
        public StringFilter? customerName { get; set; }

        [JsonPropertyName("name")]
        public StringFilter? name { get; set; }

        [JsonPropertyName("startPrice")]
        public Decimal2? startPrice { get; set; }

        [JsonPropertyName("publishDate")]
        public DateTime2? publishDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTime2? endDate { get; set; }

        [JsonPropertyName("id")]
        public Int32? id { get; set; }

        [JsonPropertyName("isParticipatedIn")]
        public bool? isParticipatedIn { get; set; }

        [JsonPropertyName("isMine")]
        public bool? isMine { get; set; }
    }

    public class SearchQueryListDto3
    {
        [JsonPropertyName("status")]
        public StatusEnum3? status { get; set; }

        [JsonPropertyName("company")]
        public SearchQueryCompanyDto? company { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("federalLaw")]
        public FederalLawEnum? federalLaw { get; set; }

        [JsonPropertyName("conclusionReason")]
        public ConclusionReasonEnum? conclusionReason { get; set; }

        [JsonPropertyName("startPrice")]
        public double? startPrice { get; set; }

        [JsonPropertyName("beginDate")]
        public DateTimeOffset? beginDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class DeliveryToCompanyQueryDto
    {
        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("kpp")]
        public string? kpp { get; set; }

        [JsonPropertyName("typeId")]
        public int? typeId { get; set; }

        [JsonPropertyName("legalAddress")]
        public string? legalAddress { get; set; }

        [JsonPropertyName("actualAddress")]
        public string? actualAddress { get; set; }
    }

    public class ContractExecutionCustomsDeclarationInfoQueryDto
    {
        [JsonPropertyName("registrationNumber")]
        public string? registrationNumber { get; set; }

        [JsonPropertyName("country")]
        public CodeNamedEntityDto? country { get; set; }
    }

    public class ContractExecutionItemBaseQueryDto
    {
        [JsonPropertyName("contractExecutionItemId")]
        public int? contractExecutionItemId { get; set; }

        [JsonPropertyName("detail")]
        public ContractExecutionItemDetailQueryDto? detail { get; set; }

        [JsonPropertyName("isSelected")]
        public bool? isSelected { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("amount")]
        public double? amount { get; set; }

        [JsonPropertyName("amountWithoutNds")]
        public double? amountWithoutNds { get; set; }

        [JsonPropertyName("ndsAmount")]
        public double? ndsAmount { get; set; }

        [JsonPropertyName("parentId")]
        public string? parentId { get; set; }

        [JsonPropertyName("id")]
        public string? id { get; set; }
    }

    public class ContractExecutionItemDetailQueryDto
    {
        [JsonPropertyName("contractExecutionItemId")]
        public int? contractExecutionItemId { get; set; }

        [JsonPropertyName("quantity")]
        public double? quantity { get; set; }

        [JsonPropertyName("ndsRateValue")]
        public double? ndsRateValue { get; set; }

        [JsonPropertyName("ndsRateString")]
        public string? ndsRateString { get; set; }

        [JsonPropertyName("exciseTax")]
        public double? exciseTax { get; set; }

        [JsonPropertyName("customsDeclarationInfo")]
        public List<ContractExecutionCustomsDeclarationInfoQueryDto>? customsDeclarationInfo { get; set; }

        [JsonPropertyName("countryId")]
        public int? countryId { get; set; }

        [JsonPropertyName("countryCode")]
        public string? countryCode { get; set; }

        [JsonPropertyName("skuId")]
        public int? skuId { get; set; }

        [JsonPropertyName("skuName")]
        public string? skuName { get; set; }

        [JsonPropertyName("supplierCode")]
        public string? supplierCode { get; set; }

        [JsonPropertyName("series")]
        public string? series { get; set; }

        [JsonPropertyName("shelfLife")]
        public DateTimeOffset? shelfLife { get; set; }

        [JsonPropertyName("ktruId")]
        public int? ktruId { get; set; }

        [JsonPropertyName("costPerUnitNoNds")]
        public double? costPerUnitNoNds { get; set; }

        [JsonPropertyName("traceableInfo")]
        public List<ContractExecutionTraceableInfoQueryDto>? traceableInfo { get; set; }

        [JsonPropertyName("markingInfo")]
        public List<ContractExecutionMarkingInfoQueryDto>? markingInfo { get; set; }

        [JsonPropertyName("id")]
        public string? id { get; set; }
    }

    public class ContractExecutionItemQueryDto
    {
        [JsonPropertyName("contractItemCostPerUnit")]
        public double? contractItemCostPerUnit { get; set; }

        [JsonPropertyName("contractItemAmount")]
        public double? contractItemAmount { get; set; }

        [JsonPropertyName("contractItemProductType")]
        public ProductTypeEnum? contractItemProductType { get; set; }

        [JsonPropertyName("contractItemProductionCode")]
        public string? contractItemProductionCode { get; set; }

        [JsonPropertyName("quantity")]
        public double? quantity { get; set; }

        [JsonPropertyName("amount")]
        public double? amount { get; set; }

        [JsonPropertyName("amountWithoutNds")]
        public double? amountWithoutNds { get; set; }

        [JsonPropertyName("contractItemAmountWithoutNds")]
        public double? contractItemAmountWithoutNds { get; set; }

        [JsonPropertyName("ndsAmount")]
        public double? ndsAmount { get; set; }

        [JsonPropertyName("contractItemQuantity")]
        public double? contractItemQuantity { get; set; }

        [JsonPropertyName("okeiName")]
        public string? okeiName { get; set; }

        [JsonPropertyName("contractItemSkuId")]
        public int? contractItemSkuId { get; set; }

        [JsonPropertyName("contractItemId")]
        public int? contractItemId { get; set; }

        [JsonPropertyName("isMedicines")]
        public bool? isMedicines { get; set; }

        [JsonPropertyName("skuExternalId")]
        public int? skuExternalId { get; set; }

        [JsonPropertyName("isGoods")]
        public bool? isGoods { get; set; }

        [JsonPropertyName("contractExecutionId")]
        public string? contractExecutionId { get; set; }

        [JsonPropertyName("items")]
        public List<ContractExecutionItemBaseQueryDto>? items { get; set; }

        [JsonPropertyName("eisObjectGuid")]
        public string? eisObjectGuid { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractExecutionMarkingInfoQueryDto
    {
        [JsonPropertyName("transportPackageIdentifier")]
        public string? transportPackageIdentifier { get; set; }

        [JsonPropertyName("identifierSign")]
        public string? identifierSign { get; set; }

        [JsonPropertyName("transportPackageSecondIdentifier")]
        public string? transportPackageSecondIdentifier { get; set; }
    }

    public class ContractExecutionQueryDto
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("number")]
        public int? number { get; set; }

        [JsonPropertyName("contractDeliveryPeriodFrom")]
        public DateTimeOffset? contractDeliveryPeriodFrom { get; set; }

        [JsonPropertyName("contractDeliveryPeriodTo")]
        public DateTimeOffset? contractDeliveryPeriodTo { get; set; }

        [JsonPropertyName("contractEntityId")]
        public int? contractEntityId { get; set; }

        [JsonPropertyName("contractSubject")]
        public string? contractSubject { get; set; }

        [JsonPropertyName("contractRegisterNumber")]
        public string? contractRegisterNumber { get; set; }

        [JsonPropertyName("contractNumber")]
        public string? contractNumber { get; set; }

        [JsonPropertyName("deliveryFromCompanyId")]
        public string? deliveryFromCompanyId { get; set; }

        [JsonPropertyName("deliveryInfoFromAddress")]
        public string? deliveryInfoFromAddress { get; set; }

        [JsonPropertyName("deliveryToCompanyId")]
        public string? deliveryToCompanyId { get; set; }

        [JsonPropertyName("deliveryInfoToAddress")]
        public string? deliveryInfoToAddress { get; set; }

        [JsonPropertyName("contractRubSum")]
        public double? contractRubSum { get; set; }

        [JsonPropertyName("items")]
        public List<ContractExecutionItemQueryDto>? items { get; set; }

        [JsonPropertyName("shippingDate")]
        public DateTimeOffset? shippingDate { get; set; }

        [JsonPropertyName("shippingInfo")]
        public string? shippingInfo { get; set; }

        [JsonPropertyName("shippingComment")]
        public string? shippingComment { get; set; }

        [JsonPropertyName("shippingResponsiblePersonPosition")]
        public string? shippingResponsiblePersonPosition { get; set; }

        [JsonPropertyName("shippingResponsiblePersonFio")]
        public string? shippingResponsiblePersonFio { get; set; }

        [JsonPropertyName("shippingCompanyInfoDocCompiler")]
        public string? shippingCompanyInfoDocCompiler { get; set; }

        [JsonPropertyName("stateName")]
        public string? stateName { get; set; }

        [JsonPropertyName("signerInfo")]
        public string? signerInfo { get; set; }

        [JsonPropertyName("signerFio")]
        public string? signerFio { get; set; }

        [JsonPropertyName("state")]
        public NamedEntityDto? state { get; set; }

        [JsonPropertyName("totalFullSum")]
        public double? totalFullSum { get; set; }

        [JsonPropertyName("totalNdsSum")]
        public double? totalNdsSum { get; set; }

        [JsonPropertyName("totalNoNdsSum")]
        public double? totalNoNdsSum { get; set; }

        [JsonPropertyName("penalty")]
        public double? penalty { get; set; }

        [JsonPropertyName("penaltyReason")]
        public string? penaltyReason { get; set; }

        [JsonPropertyName("fine")]
        public double? fine { get; set; }

        [JsonPropertyName("fineReason")]
        public string? fineReason { get; set; }

        [JsonPropertyName("defaultInterest")]
        public double? defaultInterest { get; set; }

        [JsonPropertyName("defaultInterestReason")]
        public string? defaultInterestReason { get; set; }

        [JsonPropertyName("advancePaymentAmount")]
        public double? advancePaymentAmount { get; set; }

        [JsonPropertyName("advancePaymentPercent")]
        public double? advancePaymentPercent { get; set; }

        [JsonPropertyName("stagePlanSumm")]
        public double? stagePlanSumm { get; set; }

        [JsonPropertyName("stageId")]
        public int? stageId { get; set; }

        [JsonPropertyName("stageName")]
        public string? stageName { get; set; }

        [JsonPropertyName("contractIndefiniteVolume")]
        public bool? contractIndefiniteVolume { get; set; }

        [JsonPropertyName("supplierName")]
        public string? supplierName { get; set; }

        [JsonPropertyName("ipRegistrationData")]
        public string? ipRegistrationData { get; set; }

        [JsonPropertyName("customerName")]
        public string? customerName { get; set; }

        [JsonPropertyName("supplierDateOnTax")]
        public DateTimeOffset? supplierDateOnTax { get; set; }

        [JsonPropertyName("hasChildren")]
        public bool? hasChildren { get; set; }

        [JsonPropertyName("parentId")]
        public string? parentId { get; set; }

        [JsonPropertyName("contractDeliveryId")]
        public int? contractDeliveryId { get; set; }

        [JsonPropertyName("parentStateId")]
        public int? parentStateId { get; set; }

        [JsonPropertyName("deliveryInfoFromCompanyAccountId")]
        public int? deliveryInfoFromCompanyAccountId { get; set; }

        [JsonPropertyName("supplierCompanyId")]
        public int? supplierCompanyId { get; set; }

        [JsonPropertyName("buyerCompanyId")]
        public int? buyerCompanyId { get; set; }
    }

    public class ContractExecutionQueryListDto2
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("contractId")]
        public int? contractId { get; set; }

        [JsonPropertyName("contractRegisterNumber")]
        public string? contractRegisterNumber { get; set; }

        [JsonPropertyName("contractSubject")]
        public string? contractSubject { get; set; }

        [JsonPropertyName("stateId")]
        public int? stateId { get; set; }

        [JsonPropertyName("stateName")]
        public string? stateName { get; set; }

        [JsonPropertyName("totalFullSum")]
        public double? totalFullSum { get; set; }

        [JsonPropertyName("createDate")]
        public DateTimeOffset? createDate { get; set; }

        [JsonPropertyName("contractDeliveryPeriodFrom")]
        public DateTimeOffset? contractDeliveryPeriodFrom { get; set; }

        [JsonPropertyName("contractDeliveryPeriodTo")]
        public DateTimeOffset? contractDeliveryPeriodTo { get; set; }

        [JsonPropertyName("documentNumber")]
        public string? documentNumber { get; set; }

        [JsonPropertyName("documentDate")]
        public DateTimeOffset? documentDate { get; set; }

        [JsonPropertyName("requiresAction")]
        public bool? requiresAction { get; set; }
    }

    public class ContractExecutionTraceableInfoQueryDto
    {
        [JsonPropertyName("okei")]
        public CodeNamedEntityDto? okei { get; set; }

        [JsonPropertyName("quantity")]
        public double? quantity { get; set; }

        [JsonPropertyName("batchRegNum")]
        public string? batchRegNum { get; set; }
    }

    public class ContractExecutionSearchQueryFilterDto
    {
        [JsonPropertyName("contractIds")]
        public Int32? contractIds { get; set; }

        [JsonPropertyName("ids")]
        public String2? ids { get; set; }

        [JsonPropertyName("contractRegisterNumbers")]
        public String2? contractRegisterNumbers { get; set; }

        [JsonPropertyName("contractSubject")]
        public StringFilter? contractSubject { get; set; }

        [JsonPropertyName("createDate")]
        public DateTime2? createDate { get; set; }

        [JsonPropertyName("periodFrom")]
        public DateTime2? periodFrom { get; set; }

        [JsonPropertyName("periodTo")]
        public DateTime2? periodTo { get; set; }

        [JsonPropertyName("shippingDate")]
        public DateTime2? shippingDate { get; set; }

        [JsonPropertyName("totalFullSum")]
        public double? totalFullSum { get; set; }
    }

    public class GetQuery2
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }
    }

    public class SearchQuery2
    {
        [JsonPropertyName("filter")]
        public ContractExecutionSearchQueryFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class ContractBuyerSignerQueryDto
    {
        [JsonPropertyName("position")]
        public string? position { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractCompanyBankAccountQueryDto
    {
        [JsonPropertyName("bik")]
        public string? bik { get; set; }

        [JsonPropertyName("currentAccount")]
        public string? currentAccount { get; set; }

        [JsonPropertyName("correspondentAccount")]
        public string? correspondentAccount { get; set; }

        [JsonPropertyName("personalAccount")]
        public string? personalAccount { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractCompanyContactInfoQueryDto
    {
        [JsonPropertyName("email")]
        public string? email { get; set; }

        [JsonPropertyName("phone")]
        public string? phone { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractCompanyQueryDto
    {
        [JsonPropertyName("customerId")]
        public int? customerId { get; set; }

        [JsonPropertyName("supplierId")]
        public int? supplierId { get; set; }

        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("kpp")]
        public string? kpp { get; set; }

        [JsonPropertyName("ogrn")]
        public string? ogrn { get; set; }

        [JsonPropertyName("typeId")]
        public int? typeId { get; set; }

        [JsonPropertyName("actualAddress")]
        public string? actualAddress { get; set; }

        [JsonPropertyName("legalAddress")]
        public string? legalAddress { get; set; }

        [JsonPropertyName("bankAccounts")]
        public List<ContractCompanyBankAccountQueryDto>? bankAccounts { get; set; }

        [JsonPropertyName("contactInfos")]
        public List<ContractCompanyContactInfoQueryDto>? contactInfos { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractDeliveryItemQueryDto
    {
        [JsonPropertyName("quantity")]
        public double? quantity { get; set; }

        [JsonPropertyName("contractItemId")]
        public int? contractItemId { get; set; }

        [JsonPropertyName("contractItemEntityId")]
        public string? contractItemEntityId { get; set; }

        [JsonPropertyName("contractItemName")]
        public string? contractItemName { get; set; }

        [JsonPropertyName("contractItemOfferId")]
        public int? contractItemOfferId { get; set; }

        [JsonPropertyName("contractItemCostPerUnit")]
        public double? contractItemCostPerUnit { get; set; }

        [JsonPropertyName("contractItemOkeiName")]
        public string? contractItemOkeiName { get; set; }

        [JsonPropertyName("contractItemExternalId")]
        public string? contractItemExternalId { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractDeliveryQueryDto
    {
        [JsonPropertyName("deliveryPlace")]
        public string? deliveryPlace { get; set; }

        [JsonPropertyName("periodDaysFrom")]
        public int? periodDaysFrom { get; set; }

        [JsonPropertyName("periodDaysTo")]
        public int? periodDaysTo { get; set; }

        [JsonPropertyName("periodFrom")]
        public DateTimeOffset? periodFrom { get; set; }

        [JsonPropertyName("periodTo")]
        public DateTimeOffset? periodTo { get; set; }

        [JsonPropertyName("items")]
        public List<ContractDeliveryItemQueryDto>? items { get; set; }

        [JsonPropertyName("contractExecution")]
        public List<String>? contractExecution { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractDeliveryToCompanyQueryDto
    {
        [JsonPropertyName("deliveryToCompanies")]
        public List<DeliveryToCompanyQueryDto>? deliveryToCompanies { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractItemQueryDto
    {
        [JsonPropertyName("offerId")]
        public int? offerId { get; set; }

        [JsonPropertyName("skuId")]
        public int? skuId { get; set; }

        [JsonPropertyName("quantity")]
        public double? quantity { get; set; }

        [JsonPropertyName("costPerUnit")]
        public double? costPerUnit { get; set; }

        [JsonPropertyName("costPerUnitWithoutNds")]
        public double? costPerUnitWithoutNds { get; set; }

        [JsonPropertyName("amount")]
        public double? amount { get; set; }

        [JsonPropertyName("amountWithoutNds")]
        public double? amountWithoutNds { get; set; }

        [JsonPropertyName("ndsRate")]
        public NdsRateDto? ndsRate { get; set; }

        [JsonPropertyName("okei")]
        public CodeNamedEntityDto? okei { get; set; }

        [JsonPropertyName("oksm")]
        public CodeNamedEntityDto? oksm { get; set; }

        [JsonPropertyName("okpd")]
        public CodeNamedEntityDto? okpd { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractListQueryDto2
    {
        [JsonPropertyName("federalLawName")]
        public string? federalLawName { get; set; }

        [JsonPropertyName("externalSystem")]
        public ExternalSystemEnum? externalSystem { get; set; }

        [JsonPropertyName("entityId")]
        public int? entityId { get; set; }

        [JsonPropertyName("customerInn")]
        public string? customerInn { get; set; }

        [JsonPropertyName("supplierInn")]
        public string? supplierInn { get; set; }

        [JsonPropertyName("number")]
        public string? number { get; set; }

        [JsonPropertyName("registerNumber")]
        public string? registerNumber { get; set; }

        [JsonPropertyName("conclusionDate")]
        public DateTimeOffset? conclusionDate { get; set; }

        [JsonPropertyName("rubSum")]
        public double? rubSum { get; set; }

        [JsonPropertyName("subject")]
        public string? subject { get; set; }

        [JsonPropertyName("type")]
        public ContractTypeEnum? type { get; set; }

        [JsonPropertyName("customer")]
        public NamedEntityDto? customer { get; set; }

        [JsonPropertyName("customerRegionName")]
        public string? customerRegionName { get; set; }

        [JsonPropertyName("supplier")]
        public NamedEntityDto? supplier { get; set; }

        [JsonPropertyName("tenderRegisterNumber")]
        public string? tenderRegisterNumber { get; set; }

        [JsonPropertyName("needId")]
        public int? needId { get; set; }

        [JsonPropertyName("auctionId")]
        public int? auctionId { get; set; }

        [JsonPropertyName("state")]
        public NamedEntityDto? state { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractQueryDto
    {
        [JsonPropertyName("type")]
        public ContractTypeEnum2? type { get; set; }

        [JsonPropertyName("auction")]
        public NamedEntityDto? auction { get; set; }

        [JsonPropertyName("need")]
        public NamedEntityDto? need { get; set; }

        [JsonPropertyName("purchaseRequest")]
        public NamedEntityDto? purchaseRequest { get; set; }

        [JsonPropertyName("publicState")]
        public NamedEntityDto? publicState { get; set; }

        [JsonPropertyName("internalState")]
        public NamedEntityDto? internalState { get; set; }

        [JsonPropertyName("buyerCompany")]
        public ContractCompanyQueryDto? buyerCompany { get; set; }

        [JsonPropertyName("purchaseByType")]
        public PurchaseByTypeEnum? purchaseByType { get; set; }

        [JsonPropertyName("rubSum")]
        public double? rubSum { get; set; }

        [JsonPropertyName("supplierCompany")]
        public ContractCompanyQueryDto? supplierCompany { get; set; }

        [JsonPropertyName("registerNumber")]
        public string? registerNumber { get; set; }

        [JsonPropertyName("number")]
        public string? number { get; set; }

        [JsonPropertyName("federalLaw")]
        public NamedEntityDto? federalLaw { get; set; }

        [JsonPropertyName("beginDate")]
        public DateTimeOffset? beginDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("beginDateIsConclusionDate")]
        public bool? beginDateIsConclusionDate { get; set; }

        [JsonPropertyName("conclusionDate")]
        public DateTimeOffset? conclusionDate { get; set; }

        [JsonPropertyName("subject")]
        public string? subject { get; set; }

        [JsonPropertyName("ikz")]
        public string? ikz { get; set; }

        [JsonPropertyName("financeSource")]
        public string? financeSource { get; set; }

        [JsonPropertyName("conclusionPlace")]
        public string? conclusionPlace { get; set; }

        [JsonPropertyName("conclusionReason")]
        public NamedEntityDto? conclusionReason { get; set; }

        [JsonPropertyName("placingOrder")]
        public NamedEntityDto? placingOrder { get; set; }

        [JsonPropertyName("buyerSigner")]
        public ContractBuyerSignerQueryDto? buyerSigner { get; set; }

        [JsonPropertyName("advancePaymentAmount")]
        public double? advancePaymentAmount { get; set; }

        [JsonPropertyName("advancePaymentPercent")]
        public double? advancePaymentPercent { get; set; }

        [JsonPropertyName("items")]
        public List<ContractItemQueryDto>? items { get; set; }

        [JsonPropertyName("deliveryItems")]
        public List<ContractDeliveryQueryDto>? deliveryItems { get; set; }

        [JsonPropertyName("ndsAbsenceReason")]
        public string? ndsAbsenceReason { get; set; }

        [JsonPropertyName("isGuaranteeRequired")]
        public bool? isGuaranteeRequired { get; set; }

        [JsonPropertyName("guaranteeAmount")]
        public double? guaranteeAmount { get; set; }

        [JsonPropertyName("needSupplier")]
        public NeedSupplierControlListQueryDto? needSupplier { get; set; }

        [JsonPropertyName("requiredDate")]
        public DateTimeOffset? requiredDate { get; set; }

        [JsonPropertyName("stages")]
        public List<ContractStageQueryDto>? stages { get; set; }

        [JsonPropertyName("externalSystem")]
        public ExternalSystemEnum? externalSystem { get; set; }

        [JsonPropertyName("deliveryToCompanies")]
        public List<DeliveryToCompanyQueryDto>? deliveryToCompanies { get; set; }

        [JsonPropertyName("priceFormula")]
        public bool? priceFormula { get; set; }

        [JsonPropertyName("indefiniteVolume")]
        public bool? indefiniteVolume { get; set; }

        [JsonPropertyName("multipleConsignees")]
        public bool? multipleConsignees { get; set; }

        [JsonPropertyName("deliveryByConsigneeRequest")]
        public bool? deliveryByConsigneeRequest { get; set; }

        [JsonPropertyName("industrySpecialization")]
        public IndustrySpecializationEnum? industrySpecialization { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractStageQueryDto
    {
        [JsonPropertyName("number")]
        public string? number { get; set; }

        [JsonPropertyName("planDate")]
        public DateTimeOffset? planDate { get; set; }

        [JsonPropertyName("externalId")]
        public int? externalId { get; set; }

        [JsonPropertyName("planSumm")]
        public double? planSumm { get; set; }

        [JsonPropertyName("advancePaymentAmount")]
        public double? advancePaymentAmount { get; set; }

        [JsonPropertyName("advancePaymentPercent")]
        public double? advancePaymentPercent { get; set; }

        [JsonPropertyName("guid")]
        public string? guid { get; set; }

        [JsonPropertyName("eisGuid")]
        public string? eisGuid { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class MedicationsContractListQueryDto2
    {
        [JsonPropertyName("skuList")]
        public List<ContractSkuDto>? skuList { get; set; }

        [JsonPropertyName("number")]
        public string? number { get; set; }

        [JsonPropertyName("registerNumber")]
        public string? registerNumber { get; set; }

        [JsonPropertyName("conclusionDate")]
        public DateTimeOffset? conclusionDate { get; set; }

        [JsonPropertyName("rubSum")]
        public double? rubSum { get; set; }

        [JsonPropertyName("subject")]
        public string? subject { get; set; }

        [JsonPropertyName("type")]
        public ContractTypeEnum? type { get; set; }

        [JsonPropertyName("customer")]
        public NamedEntityDto? customer { get; set; }

        [JsonPropertyName("customerRegionName")]
        public string? customerRegionName { get; set; }

        [JsonPropertyName("supplier")]
        public NamedEntityDto? supplier { get; set; }

        [JsonPropertyName("tenderRegisterNumber")]
        public string? tenderRegisterNumber { get; set; }

        [JsonPropertyName("needId")]
        public int? needId { get; set; }

        [JsonPropertyName("auctionId")]
        public int? auctionId { get; set; }

        [JsonPropertyName("state")]
        public NamedEntityDto? state { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class NeedSupplierControlListQueryDto
    {
        [JsonPropertyName("supplierId")]
        public int? supplierId { get; set; }

        [JsonPropertyName("supplierName")]
        public string? supplierName { get; set; }

        [JsonPropertyName("companyId")]
        public int? companyId { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("cost")]
        public double? cost { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class ContractSearchQueryFilterDto
    {
        [JsonPropertyName("type")]
        public ContractTypeEnum3? type { get; set; }

        [JsonPropertyName("customerRegionTreePathId")]
        public String2? customerRegionTreePathId { get; set; }

        [JsonPropertyName("subject")]
        public StringFilter? subject { get; set; }

        [JsonPropertyName("conclusionReason")]
        public Int32? conclusionReason { get; set; }

        [JsonPropertyName("rubSum")]
        public Decimal2? rubSum { get; set; }

        [JsonPropertyName("conclusionDate")]
        public DateTime2? conclusionDate { get; set; }

        [JsonPropertyName("beginEndDate")]
        public DateTime2? beginEndDate { get; set; }

        [JsonPropertyName("supplierKeyword")]
        public StringFilter? supplierKeyword { get; set; }

        [JsonPropertyName("customerKeyword")]
        public StringFilter? customerKeyword { get; set; }

        [JsonPropertyName("number")]
        public StringFilter? number { get; set; }

        [JsonPropertyName("registerNumber")]
        public StringFilter? registerNumber { get; set; }

        [JsonPropertyName("placingOrder")]
        public Int32? placingOrder { get; set; }

        [JsonPropertyName("offerRegisterNumber")]
        public StringFilter? offerRegisterNumber { get; set; }

        [JsonPropertyName("federalLaw")]
        public Int32? federalLaw { get; set; }

        [JsonPropertyName("manualRegistered")]
        public bool? manualRegistered { get; set; }

        [JsonPropertyName("purchaseRegisterNumber")]
        public StringFilter? purchaseRegisterNumber { get; set; }

        [JsonPropertyName("isQuantityUnknown")]
        public bool? isQuantityUnknown { get; set; }

        [JsonPropertyName("state")]
        public Int32? state { get; set; }

        [JsonPropertyName("ids")]
        public Int32? ids { get; set; }

        [JsonPropertyName("productionTreePathId")]
        public String2? productionTreePathId { get; set; }
    }

    public class ReportQuery
    {
        [JsonPropertyName("filter")]
        public ContractSearchQueryFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class GetContractDeliveryToCompanyQuery
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;
    }

    public class GetQuery3
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;
    }

    public class MedicationsSearchQuery
    {
        [JsonPropertyName("filter")]
        public ContractSearchQueryFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SearchQuery3
    {
        [JsonPropertyName("filter")]
        public ContractSearchQueryFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public enum SkuQueryOfferTypeEnum
    {
        averagePrice,
        minimalPrice,
        recommendedPrice,
        referencePrice,
    }

    public class GetQueryDataDto2
    {
        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("status")]
        public StatusEnum4? status { get; set; }

        [JsonPropertyName("company")]
        public SearchQueryCompanyDto? company { get; set; }

        [JsonPropertyName("federalLaw")]
        public FederalLawEnum? federalLaw { get; set; }

        [JsonPropertyName("conclusionReason")]
        public ConclusionReasonEnum? conclusionReason { get; set; }

        [JsonPropertyName("nmck")]
        public double? nmck { get; set; }

        [JsonPropertyName("beginDate")]
        public DateTimeOffset? beginDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("isQuantityUnknown")]
        public bool? isQuantityUnknown { get; set; }

        [JsonPropertyName("itemsCount")]
        public int? itemsCount { get; set; }

        [JsonPropertyName("regionId")]
        public int? regionId { get; set; }

        [JsonPropertyName("winner")]
        public SearchQueryCompanyDto? winner { get; set; }
    }

    public class SearchQueryFilterDto2
    {
        [JsonPropertyName("status")]
        public StatusEnum2? status { get; set; }

        [JsonPropertyName("customerInn")]
        public String2? customerInn { get; set; }

        [JsonPropertyName("customerName")]
        public StringFilter? customerName { get; set; }

        [JsonPropertyName("name")]
        public StringFilter? name { get; set; }

        [JsonPropertyName("startPrice")]
        public Decimal2? startPrice { get; set; }

        [JsonPropertyName("publishDate")]
        public DateTime2? publishDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTime2? endDate { get; set; }

        [JsonPropertyName("id")]
        public Int32? id { get; set; }

        [JsonPropertyName("isParticipatedIn")]
        public bool? isParticipatedIn { get; set; }

        [JsonPropertyName("isMine")]
        public bool? isMine { get; set; }
    }

    public class SearchQueryListDto4
    {
        [JsonPropertyName("status")]
        public StatusEnum4? status { get; set; }

        [JsonPropertyName("company")]
        public SearchQueryCompanyDto? company { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("federalLaw")]
        public FederalLawEnum? federalLaw { get; set; }

        [JsonPropertyName("conclusionReason")]
        public ConclusionReasonEnum? conclusionReason { get; set; }

        [JsonPropertyName("startPrice")]
        public double? startPrice { get; set; }

        [JsonPropertyName("beginDate")]
        public DateTimeOffset? beginDate { get; set; }

        [JsonPropertyName("endDate")]
        public DateTimeOffset? endDate { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class GetQuery4
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;
    }

    public class SearchQuery4
    {
        [JsonPropertyName("filter")]
        public SearchQueryFilterDto2? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class UploadStateQuery
    {
        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }
    }

    public class UploadStateSearchQuery
    {
        [JsonPropertyName("filter")]
        public UploadStateSearchFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SearchQuery5
    {
        [JsonPropertyName("filter")]
        public OkpdQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SearchQuery6
    {
        [JsonPropertyName("filter")]
        public ProductionDirectoryQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SearchQuery7
    {
        [JsonPropertyName("filter")]
        public ProductionQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SearchQueryCompanyDto
    {
        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class OkpdQueryFilter
    {
        [JsonPropertyName("code")]
        public StringFilter? code { get; set; }

        [JsonPropertyName("ids")]
        public Int32? ids { get; set; }

        [JsonPropertyName("parentIds")]
        public Int322? parentIds { get; set; }

        [JsonPropertyName("name")]
        public StringFilter? name { get; set; }

        [JsonPropertyName("isLastLevel")]
        public bool? isLastLevel { get; set; }
    }

    public class ProductionDirectoryQueryFilter
    {
        [JsonPropertyName("productionIds")]
        public Int322? productionIds { get; set; }

        [JsonPropertyName("entityState")]
        public int? entityState { get; set; }

        [JsonPropertyName("ids")]
        public Int32? ids { get; set; }

        [JsonPropertyName("parentIds")]
        public Int322? parentIds { get; set; }

        [JsonPropertyName("name")]
        public StringFilter? name { get; set; }

        [JsonPropertyName("isLastLevel")]
        public bool? isLastLevel { get; set; }
    }

    public class ProductionQueryFilter
    {
        [JsonPropertyName("code")]
        public StringFilter? code { get; set; }

        [JsonPropertyName("isInnovation")]
        public bool? isInnovation { get; set; }

        [JsonPropertyName("ids")]
        public Int32? ids { get; set; }

        [JsonPropertyName("parentIds")]
        public Int322? parentIds { get; set; }

        [JsonPropertyName("name")]
        public StringFilter? name { get; set; }

        [JsonPropertyName("isLastLevel")]
        public bool? isLastLevel { get; set; }
    }

    public class BetsQuery
    {
        [JsonPropertyName("auctionId")]
        public int auctionId { get; set; } = default!;
    }

    public class DownloadFileQuery2
    {
        [JsonPropertyName("fileId")]
        public int? fileId { get; set; }

        [JsonPropertyName("bankGuaranteeId")]
        public string? bankGuaranteeId { get; set; }
    }

    public class GetSupplierCatalogQuery
    {
        [JsonPropertyName("filter")]
        public SupplierCatalogQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SupplierCatalogQueryFilter
    {
        [JsonPropertyName("offerIds")]
        public Int32? offerIds { get; set; }
    }

    public class DownloadFileQuery3
    {
        [JsonPropertyName("id")]
        public int? id { get; set; }
    }

    public class DownloadFileSignatureQuery
    {
        [JsonPropertyName("signatureId")]
        public int? signatureId { get; set; }
    }

    public class GetProductionCharacteristicsReferenceQuery
    {
        [JsonPropertyName("kpgzCode")]
        public string? kpgzCode { get; set; }

        [JsonPropertyName("productionDirectoryId")]
        public int? productionDirectoryId { get; set; }
    }

    public class GetStatisticsMkrQuery
    {
        [JsonPropertyName("filter")]
        public StatisticsQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class GetStatisticsQuery
    {
        [JsonPropertyName("filter")]
        public StatisticsQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class StatisticsQueryFilter
    {
        [JsonPropertyName("aggregateTypeId")]
        public AggregateTypeEnum? aggregateTypeId { get; set; }

        [JsonPropertyName("date")]
        public DateTime2? date { get; set; }

        [JsonPropertyName("entityId")]
        public String2? entityId { get; set; }

        [JsonPropertyName("entityTypeId")]
        public string? entityTypeId { get; set; }

        [JsonPropertyName("valueTypeId")]
        public Guid? valueTypeId { get; set; }
    }

    public class GetDetailsQuery
    {
        [JsonPropertyName("filter")]
        public GetDetailsFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class SearchQuery8
    {
        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("filter")]
        public SearchFilterDto? filter { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class GetQuery5
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;

        [JsonPropertyName("offerType")]
        public SkuQueryOfferTypeEnum? offerType { get; set; }
    }

    public class SearchQuery9
    {
        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("filter")]
        public SkuFilterDto? filter { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }

    public class GetQuery6
    {
        [JsonPropertyName("year")]
        public int year { get; set; } = default!;

        [JsonPropertyName("valueType")]
        public StatisticsTypeEnum? valueType { get; set; }
    }
}
