// <auto-generated />
using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Zakupki.MosApi
{
    public partial class MosSwaggerClient
    {
        public async Task<OkpdListDto?> ReferencesGetokpdreferenceAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/references/GetOkpdReference");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<OkpdListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<ProductionDirectoryListDto?> ReferencesGetproductiondirectoryreferenceAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/references/GetProductionDirectoryReference");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ProductionDirectoryListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<ProductionListDto?> ReferencesGetproductionreferenceAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/references/GetProductionReference");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ProductionListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<List<RegionListDto>?> ReferencesGetregionsreferenceAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/references/GetRegionsReference");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<List<RegionListDto>>(stream, _serializerOptions, cancellationToken);
        }
    }
}
