// <auto-generated />
using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Zakupki.MosApi
{
    public partial class MosSwaggerClient
    {
        public async Task<ContractListDto?> QueriesGetcontractsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetContracts");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ContractListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<ContractListDto?> QueriesGetcontractstatsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetContractStats");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ContractListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<CustomerListDto?> QueriesGetcustomersAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetCustomers");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<CustomerListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SkuChangeRequestListDto?> QueriesGetexternalskuchangerequestsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetExternalSkuChangeRequests");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SkuChangeRequestListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<ExtendSkuListDto?> QueriesGetexternalskusAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetExternalSkus");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ExtendSkuListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<OfferListDto?> QueriesGetoffersAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetOffers");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<OfferListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<List<SkuDto>?> QueriesGetskuAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSku");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<List<SkuDto>>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SkuListDto?> QueriesGetskusAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSkus");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SkuListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<List<StatisticDto>?> QueriesGetstatisticsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetStatistics");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<List<StatisticDto>>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SupplierBlockHistoryDto?> QueriesGetsupplierblockhistoryAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSupplierBlockHistory");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SupplierBlockHistoryDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<List<SupplierDto2>?> QueriesGetsuppliersbyidsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSuppliersByIds");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<List<SupplierDto2>>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SupplierDto3?> QueriesGetsuppliersAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSuppliers");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SupplierDto3>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<TenderListDto?> QueriesGettendersAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetTenders");
            var hasQuery = false;
            if (query != null)
            {
                urlBuilder.Append(hasQuery ? '&' : '?');
                urlBuilder.Append(Uri.EscapeDataString("query"));
                urlBuilder.Append('=');
                urlBuilder.Append(Uri.EscapeDataString(query.ToString()!));
                hasQuery = true;
            }
            using var request = new HttpRequestMessage(new HttpMethod("GET"), urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<TenderListDto>(stream, _serializerOptions, cancellationToken);
        }
    }
}
