// <auto-generated />
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Zakupki.MosApi
{
    public partial class MosSwaggerClient
    {
        private string? SerializeQuery(object? query)
        {
            return query switch
            {
                null => null,
                string queryString => queryString,
                _ => JsonSerializer.Serialize(query, _serializerOptions)
            };
        }

        private HttpRequestMessage CreateGetRequest(string url)
        {
            var request = new HttpRequestMessage(HttpMethod.Get, url);

            if (!string.IsNullOrWhiteSpace(_apiToken))
            {
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _apiToken);
            }

            return request;
        }

        public async Task<ContractListDto?> QueriesGetcontractsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetContracts");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ContractListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<ContractListDto?> QueriesGetcontractstatsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetContractStats");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ContractListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<CustomerListDto?> QueriesGetcustomersAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetCustomers");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<CustomerListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SkuChangeRequestListDto?> QueriesGetexternalskuchangerequestsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetExternalSkuChangeRequests");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SkuChangeRequestListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<ExtendSkuListDto?> QueriesGetexternalskusAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetExternalSkus");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<ExtendSkuListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<OfferListDto?> QueriesGetoffersAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetOffers");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<OfferListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<List<SkuDto>?> QueriesGetskuAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSku");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<List<SkuDto>>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SkuListDto?> QueriesGetskusAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSkus");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SkuListDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<List<StatisticDto>?> QueriesGetstatisticsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetStatistics");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<List<StatisticDto>>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SupplierBlockHistoryDto?> QueriesGetsupplierblockhistoryAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSupplierBlockHistory");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SupplierBlockHistoryDto>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<List<SupplierDto2>?> QueriesGetsuppliersbyidsAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSuppliersByIds");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<List<SupplierDto2>>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<SupplierDto3?> QueriesGetsuppliersAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetSuppliers");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<SupplierDto3>(stream, _serializerOptions, cancellationToken);
        }

        public async Task<TenderListDto?> QueriesGettendersAsync(object? query, CancellationToken cancellationToken = default)
        {
            var urlBuilder = new StringBuilder();
            urlBuilder.Append(_baseUrl);
            urlBuilder.Append("/api/v1/queries/GetTenders");
            var queryString = SerializeQuery(query);
            if (queryString != null)
            {
                urlBuilder.Append('?');
                urlBuilder.Append(Uri.EscapeDataString(queryString));
            }
            using var request = CreateGetRequest(urlBuilder.ToString());
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            return await JsonSerializer.DeserializeAsync<TenderListDto>(stream, _serializerOptions, cancellationToken);
        }
    }
}
