// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Zakupki.MosApi
{
    public class SkuCreationSourceEnum
    {
        [JsonPropertyName("id")]
        public SkuCreationSourceEnum2? id { get; set; }

        [JsonPropertyName("code")]
        public string? code { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }
    }



    public class NamedEntityDto
    {
        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public enum FileTypeEnum
    {
        exportManagerFile,
        generatedContract,
        contractExecutionUpd,
        contractExecutionUpdTicket,
        contractExecutionUpdConfirmation,
        contractExecutionUpdDecline,
        adminAuctionReport,
        contractExecutionUpdExternalPrintForm,
        contractExecutionUpdDeclineTicket,
        innCertificate,
        ogrnCertificate,
        shareholdersRegisterExtract,
        rightLicense,
        excecutiveApointmentOrder,
        chiefAccountantApointmentOrder,
        associationMemorandum,
        founderPassport,
        headPassport,
        chiefAccountantPassport,
        organizationOwnerPassport,
        balanceSheetLastYear,
        balanceSheetLastQuarter,
        incomeStatementLastYear,
        incomeStatementLastQuarter,
        realEstateOwnershipCertificate,
        realEstateObject,
        realEstateLeaseContract,
        approvalByAuthorizedCompany,
        bankSelection,
        bankGuaranteeRequest,
        registrationCertificateMedicalProducts,
        packagingAndLabelingRequirementsMedicalProducts,
        specialRequirementsForPackagingAndTransportationOfGoodsReagents,
        certificatesOfConformityOfGoods,
        documentsRelatedToTheProduct,
        warrantyObligationsOfTheSupplierAndTheManufacturerOfTheGoods,
        originalSignedApplicationForTheSupplyOfGoods,
        qualityOfTheGoodsInAccordanceWithTheLegislation,
        certificatesOfConformityForGroupOfGoods,
        stateRegistrationCertificate,
        fireSafetyCertificate,
        actOfAcceptanceAndDeliveryOfMaterialAssetsFromDismantling,
        otherDocumentsInAccordanceWithTheTermsOfReference,
        purchaseAttachmentContractProject,
        purchaseAttachmentTechnicalTask,
        companyProfileLogo,
        companyProfileDocument,
        companyProfilePortfolio,
        companyProfileLegalAct,
        offerAttachment,
        offerTradeAcceptionDocument,
        offerCountryConfirmDocument,
        offerRequirementsConfirmDocument,
        bankGuaranteeFile,
        bankGuaranteeContractFile,
        supportAttachments,
        skuInaccuracyAttachments,
        ymlUpload,
        contractExecutionMiniUpdZip,
        contractExecutionUpdNullify,
        xlsxPriceUpload,
        contractExecutionFnsUpdXml,
        contractExecutionEisUpdXml,
        contractExecutionUpdDocx,
        contractExecutionFnsUpdCorrXml,
        contractExecutionEisUpdCorrXml,
        contractExecutionFnsUpdBuyerTicket,
        contractExecutionEisUpdBuyerTicket,
        contractExecutionFnsUpdUkdBuyerUvUtoch,
        contractExecutionEisUpdUkdBuyerUvUtoch,
        contractExecutionMoscowXml,
        contractExecutionEisUkdXml,
        contractExecutionFnsUkdXml,
        contractExecutionFnsUkdCorrXml,
        contractExecutionEisUkdCorrXml,
        contractExecutionMoscowUpdDocx,
        contractExecutionMoscowUpdPdf,
        eisAcceptanceDocument,
        eisPriceNegotiationProtocol,
        eisPackingList,
        eisRegistrationCertificateOfMedProd,
        eisConfirmationOfGoodsConformity,
        eisRussianInstructionsForMedicalUse,
        eisSpecification,
        eisTechnicalCharacteristics,
        eisOtherDocumentsProvidedByOrder870n,
        eisPaymentAndSettlementDocument,
        eisOtherDocumentsStipulatedByContract,
        eisOriginOrManufacturerCountryInformation,
        eisPaymentDocumentsOfContractPenaltiesFines,
        eisDiscrepancyDocument,
        eisDocumentOnResultsOfExamination,
        eisDisagreementProtocol,
        eisAcceptanceCommitteeDecision,
        eisPretrialAgreement,
        eisTheCourtsDecision,
        eisBasisForPaymentDocument,
        contractExecutionUkdDocx,
        contractExecutionEisUpdDocx,
        contractExecutionRfidXml,
        eisContractXml,
        eisContractEstimateXml,
        chatMessageFile,
        needSupplierOfferDetails,
        eisMoscowUpdWithEstimateDocx,
        eisMoscowUpdWithEstimatePdf,
        actualPatent,
        declarationEnvdLastQuarter,
        declarationEsnLastYear,
        declarationUsnLastYear,
        declarationNdsLastQuarter,
        realEstatePhoto,
        realEstateEgrnRegisterExtract,
        bankGuaranteeOrder,
        bankGuaranteeAccessionApplication,
        contractExecutionEisUpdWithEstimateDocx,
        contractExecutionEisUpdWithEstimatePdf,
        bankGuaranteeAdditionallyDocuments,
        bankGuaranteeAgreementInsurance,
        bankGuaranteeInvoicePayment,
        structuredCommercialOfferForm,
        commercialOfferArchive,
        contractExecutionInvoiceDocx,
        contractExecutionInvoicePdf,
        contractExecutionCorrUkdDocx,
        contractExecutionCorrUpdDocx,
        documentsConfirmingProduction,
        contractExecutionCorrectionDocument,
        contractExecutionCorrectionInvoice,
        contractExecutionCorrectiveActWithEstimate,
        bankGuaranteePowerOfAttorneyOfSignatory,
        bankGuaranteeCopyOfPassportOfSignatory,
        bankGuaranteeRequestLimitByBank,
        bankGuaranteePrincipalFormByBank,
        bankGuaranteeAgreementProcessingPersonalDataByBank,
        bankGuaranteeDeclarationBeneficiaryOwner,
        bankGuaranteeAgentRelationAgreementByBank,
        bankGuaranteeFinReportByBank,
        bankGuaranteeOrderGuaranteeByBank,
        bankGuaranteeReferenceAbsenceOfNeedToApproveTransaction,
        bankGuaranteeOrderParamsByBank,
        bankGuaranteeOtherDocsByBank,
        bankGuaranteeFinancialStatements022022,
        bankGuaranteeCardOfTheCompanyWithIndication,
        bankGuaranteeConstituentCoOwnersLegalEntities,
        bankGuaranteeRegisterOfExecutedContracts,
        bankGuaranteeDecisionApproveMajorTransaction,
        bankGuaranteeSnilsFoundersBusinessOwners,
        bankGuaranteeChangesConstituent,
        bankGuaranteeDecisionToCreateCompany,
        bankGuaranteeTenderDocumentation,
        machineReadablePowerOfAttorneyUploadedFile,
        bankGuaranteeContract,
        bankGuaranteeInsurancePolicy,
        bankGuaranteeQuestionnaireIpL115,
        bankGuaranteeQuestionnaireFlL115,
        bankGuaranteeQuestionnaireUlL115,
        bankGuaranteeFinancialStatements012023Ip,
        bankGuaranteeFinancialStatements042022Ip,
        bankGuaranteeFinancialStatements042022,
        bankGuaranteeFinancialStatements012023,
        bankGuaranteeGroupBasicPackageOfDocuments,
        bankGuaranteeGuaranteeProject,
        bankGuaranteeAccount62WithCustomer,
        bankGuaranteeAgreementWithCustomer,
        bankGuaranteeAgreementProcessingPersonalData,
        bankGuaranteeFilePdf,
        bankGuaranteeUnknown,
        contractLicenseFile,
        contractExecutionConstructionActXml,
        machineReadablePowerOfAttorneyUploadedFileSign,
        contractExecutionFnsUkdBuyerTicket,
        contractExecutionEisUkdBuyerTicket,
        contractExecutionConstructionActEisBuyerTicket,
        eisContractExecutionEisMiniUpdZip,
        chatMessageSignedFile,
        productionCalendarImportFile,
        contractExecutionConstructionActEisSupplierTicket,
        adminNeedReport,
        gar,
        executionImportFile,
        skuMassChangetFile,
        skuChangeRequestImportFile,
        skuChangeRequestReport,
        productDirectoryAndKpgzLinksReport,
        contractReport,
        contractExecutionSpecificationReport,
        skuCatalogReport,
        fZ223ProcurementRegulations,
        procurementRegulations,
        contractProject,
        nmcCalculation,
        technicalAssignment,
        productionDirectoryImage,
        skuImage,
    }



    public enum SignatureTypeEnum
    {
        attached,
        detachedSignHash,
        noSign,
        detached,
    }



    public enum ExternalSystemEnum
    {
        pP1,
        pP2,
        em,
        rk,
        pt,
        ru,
        eaist,
        ok,
        mt,
        mvk,
        iS223,
        eaisT2,
        eM1,
        eaisT2AN,
        permianIntegration,
        hmao,
        samara,
        tambov,
        bftTumenObl,
        askd,
        yanao,
        orenburg,
        sevastopol,
        kaliningrad,
        vtbConnect,
        krasnodar,
        sPb,
        emias,
        rtsTender,
        arkhangelsk,
        mo,
        iMoscow,
        ppManualContractRegistration,
        kalugaAstral,
        kaluga,
        murmansk,
        hpsm,
        tekTorg,
        tverObl,
        primorie,
        triptoivm,
        nao,
        novgorod,
        yakutia,
        ulyanovsk,
        kurgan,
        mkr,
        eetP44FZ,
        dnpp,
        lipetsk,
        vtbBank,
        kePiZO,
        eetpB2B,
        bftSurgut,
        captcha,
        sberBankAst,
        mtsBank,
        kristaTulaobl,
        kalugaAstralExternal,
        kristaOmskobl,
        kristaNovosibobl,
        eis,
        kristaKrasnodar223,
        keysBryansk,
        kristaOrenburg223,
        kuzbass,
        mosru,
        bftNizhnygorodskayaObl,
        mosprom,
        eisEdoSupplier,
        eisEdoBuyer,
        eisEdoCabinetGuidSupplier,
        eisEdoCompanyTokenId,
        eetpszuz,
        hpsmE2,
        ppLogistics,
        eetpfinservice,
        gisp,
        egrulDit,
        manufacturersMap,
        sberLogistics,
        diadocEdoSupplier,
        diadocEdoBuyer,
        bftPenza,
        aisUid,
        eks,
        emptyFactoring,
        emptyInsurance,
        defaultAquireSystem,
        gbuac,
        novikomBank,
        telegramBot,
        bftIrkutsk,
        kristaYanao223,
        eetpCommerce,
        kristaIrkutsk,
        governmentKey,
        cpvzMDM,
        eMoscow,
        mositsm,
        bftChelyabinsk,
    }



    public class LoginModel
    {
        [JsonPropertyName("login")]
        public string? login { get; set; }

        [JsonPropertyName("password")]
        public string? password { get; set; }
    }



    public class PpIdentity
    {
        [JsonPropertyName("companyId")]
        public int? companyId { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("login")]
        public string? login { get; set; }

        [JsonPropertyName("supplierId")]
        public int? supplierId { get; set; }

        [JsonPropertyName("customerId")]
        public int? customerId { get; set; }

        [JsonPropertyName("spUserId")]
        public int? spUserId { get; set; }

        [JsonPropertyName("authorizationData")]
        public string? authorizationData { get; set; }
    }



    public class DateTimeRangeDto
    {
        [JsonPropertyName("start")]
        public DateTimeOffset? start { get; set; }

        [JsonPropertyName("end")]
        public DateTimeOffset? end { get; set; }
    }



    public class FiasAddressDto
    {
        [JsonPropertyName("fiasId")]
        public string? fiasId { get; set; }

        [JsonPropertyName("aoId")]
        public int? aoId { get; set; }

        [JsonPropertyName("fiasEntityId")]
        public string? fiasEntityId { get; set; }

        [JsonPropertyName("oktmoCode")]
        public string? oktmoCode { get; set; }

        [JsonPropertyName("oldAddress")]
        public string? oldAddress { get; set; }

        [JsonPropertyName("regionCode")]
        public string? regionCode { get; set; }

        [JsonPropertyName("city")]
        public string? city { get; set; }

        [JsonPropertyName("street")]
        public string? street { get; set; }

        [JsonPropertyName("house")]
        public string? house { get; set; }

        [JsonPropertyName("flat")]
        public string? flat { get; set; }

        [JsonPropertyName("postalCode")]
        public string? postalCode { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public enum CharacteristicValueTypeEnum
    {
        integer,
        decimal,
        date,
        boolean,
        list,
        string,
    }



    public enum CompanyTypeEnum
    {
        ul,
        fl,
        ip,
        mp,
    }



    public enum ConclusionReasonEnum
    {
        lawItem1193,
        lawItem2193,
        lawItem3193,
        lawItem4193,
        lawItem5193,
        lawItem6193,
        lawItem7193,
        lawItem8193,
        lawItem9193,
        lawItem10193,
        lawItem11193,
        lawItem12193,
        lawItem13193,
        lawItem14193,
        lawItem15193,
        lawItem16193,
        lawItem17193,
        lawItem18193,
        lawItem19193,
        lawItem20193,
        lawItem21193,
        lawItem22193,
        lawItem23193,
        lawItem24193,
        lawItem25193,
        lawItem26193,
        lawItem27193,
        lawItem28193,
        lawItem29193,
        lawItem32193,
        lawItem33193,
        lawItem35193,
        lawItem21546,
        lawItem21546A,
        lawItem124193,
        lawItem125193,
        lawItem37193,
        lawItem38193,
        lawItem39193,
        lawItem40193,
        lawItem41193,
        lawItem42193,
        lawItem43193,
        lawItem44193,
        lawItem54193,
        lawItem55193,
        lawItem30193,
    }



    public enum ContractFileTypeEnum
    {
        contract,
        differencesProtocol,
        actionPrintForm,
        attachment,
        additionalAgreement,
        terminationAgreement,
        differencesProtocolAdjustment,
        license,
        nationalRegimeAttachment,
    }



    public enum CurrencyEnum
    {
        rub,
        usd,
        euro,
    }



    public enum ExternalAuctionFileTypeEnum
    {
        contractProject,
        nmcCalculation,
        technicalAssignment,
    }



    public enum FederalLawEnum
    {
        fZ223,
        fZ94,
        fZ44,
        fZ44_fZ223,
        msK_C,
        msK_AN,
        overhaul,
        procurementRegulation,
    }



    public enum NdsRateEnum
    {
        nds_18,
        nds_10,
        nds_0,
        nds_No,
        nds_20,
        nds_5,
        nds_7,
    }



    public enum ProcedureTypeEnum
    {
        singleSupplier,
    }



    public enum PurchaseByTypeEnum
    {
        purchaseByProductQuantity,
        purchaseByProductUnitPrice,
    }



    public enum UnpublishReasonEnum
    {
        contentOrCreationError,
        double,
        integrationService,
        other,
        excessiveConsumerProperties,
        productQuantityNotMeetSpecification,
        productTypesNotMeetSpecification,
    }



    public enum VatRateEnum
    {
        nds20,
        nds10,
        nds120,
        nds110,
        nds0,
        noNds,
    }



    public enum ClaimActionTypeEnum
    {
        input,
        registered,
        needComment,
        answer,
        decision,
    }



    public enum ClaimBlockReasonEnum
    {
        reason_2_4_1_a,
        reason_2_4_1_b,
        reason_2_4_1_v,
        reason_repeated_2_4_1_a_b,
        reason_2_4_2_b,
        reason_repeated_2_4_2_a,
        reason_2_4_3_g,
        decision,
        administrator,
    }



    public enum ClaimDecisionTypeEnum
    {
        unblock,
        keepBlock,
        changeBlock,
        refused,
        return,
    }



    public class ClaimDto
    {
        [JsonPropertyName("claimId")]
        public int claimId { get; set; } = default!;

        [JsonPropertyName("claimBlockReason")]
        public ClaimBlockReasonEnum? claimBlockReason { get; set; }

        [JsonPropertyName("company")]
        public OrganisationDto? company { get; set; }

        [JsonPropertyName("content")]
        public string? content { get; set; }

        [JsonPropertyName("creationTime")]
        public DateTimeOffset creationTime { get; set; } = default!;

        [JsonPropertyName("context")]
        public string? context { get; set; }

        [JsonPropertyName("blockBeginDate")]
        public DateTimeOffset blockBeginDate { get; set; } = default!;

        [JsonPropertyName("blockEndDate")]
        public DateTimeOffset blockEndDate { get; set; } = default!;

        [JsonPropertyName("blockReasonProcedureUrl")]
        public string? blockReasonProcedureUrl { get; set; }
    }



    public class CustomerDto
    {
        [JsonPropertyName("id")]
        public int? id { get; set; }

        [JsonPropertyName("url")]
        public string? url { get; set; }
    }



    public class OrganisationDto
    {
        [JsonPropertyName("id")]
        public int id { get; set; } = default!;

        [JsonPropertyName("contacts")]
        public List<ContactInfo>? contacts { get; set; }

        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("kpp")]
        public string? kpp { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("ogrn")]
        public string? ogrn { get; set; }

        [JsonPropertyName("shortName")]
        public string? shortName { get; set; }

        [JsonPropertyName("type")]
        public CompanyTypeEnum? type { get; set; }

        [JsonPropertyName("customer")]
        public CustomerDto? customer { get; set; }

        [JsonPropertyName("supplier")]
        public SupplierDto? supplier { get; set; }
    }



    public class SupplierDto
    {
        [JsonPropertyName("id")]
        public int? id { get; set; }

        [JsonPropertyName("url")]
        public string? url { get; set; }
    }



    public class UserDto
    {
        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("phone")]
        public string? phone { get; set; }

        [JsonPropertyName("position")]
        public string? position { get; set; }

        [JsonPropertyName("email")]
        public string? email { get; set; }
    }



    public enum AuctionTypeEnum
    {
        offer,
        sku,
        characteristic,
        okpd,
        spgz,
    }



    public class BankAccountDto
    {
        [JsonPropertyName("bankCity")]
        public string? bankCity { get; set; }

        [JsonPropertyName("bankName")]
        public string? bankName { get; set; }

        [JsonPropertyName("bik")]
        public string? bik { get; set; }

        [JsonPropertyName("contractUse")]
        public bool? contractUse { get; set; }

        [JsonPropertyName("correspondent")]
        public string? correspondent { get; set; }

        [JsonPropertyName("current")]
        public string? current { get; set; }

        [JsonPropertyName("personal")]
        public string? personal { get; set; }
    }



    public class ContactInfo
    {
        [JsonPropertyName("index")]
        public string? index { get; set; }

        [JsonPropertyName("factAddress")]
        public string? factAddress { get; set; }

        [JsonPropertyName("legalAddress")]
        public string? legalAddress { get; set; }

        [JsonPropertyName("timeZone")]
        public int? timeZone { get; set; }

        [JsonPropertyName("website")]
        public string? website { get; set; }

        [JsonPropertyName("email")]
        public string? email { get; set; }

        [JsonPropertyName("fax")]
        public string? fax { get; set; }

        [JsonPropertyName("contactName")]
        public string? contactName { get; set; }

        [JsonPropertyName("phoneNumbers")]
        public List<string>? phoneNumbers { get; set; }

        [JsonPropertyName("fullNameFirst")]
        public string? fullNameFirst { get; set; }

        [JsonPropertyName("fullNameLast")]
        public string? fullNameLast { get; set; }

        [JsonPropertyName("fullNamePatronym")]
        public string? fullNamePatronym { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public class ExternalAuctionFileDto
    {
        [JsonPropertyName("type")]
        public ExternalAuctionFileTypeEnum? type { get; set; }

        [JsonPropertyName("fileUrl")]
        public string? fileUrl { get; set; }

        [JsonPropertyName("fileName")]
        public string? fileName { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public class ExternalFileDto
    {
        [JsonPropertyName("type")]
        public string? type { get; set; }

        [JsonPropertyName("fileUrl")]
        public string? fileUrl { get; set; }

        [JsonPropertyName("fileName")]
        public string? fileName { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public class FileSignature
    {
        [JsonPropertyName("data")]
        public string? data { get; set; }

        [JsonPropertyName("signatureType")]
        public SignatureTypeEnum? signatureType { get; set; }

        [JsonPropertyName("signingDate")]
        public DateTimeOffset signingDate { get; set; } = default!;

        [JsonPropertyName("url")]
        public string? url { get; set; }
    }



    public class FileStorageDto
    {
        [JsonPropertyName("fileName")]
        public string? fileName { get; set; }

        [JsonPropertyName("fileHash")]
        public string? fileHash { get; set; }

        [JsonPropertyName("fileSize")]
        public int? fileSize { get; set; }

        [JsonPropertyName("signatures")]
        public List<SignatureListDto>? signatures { get; set; }

        [JsonPropertyName("fileUrl")]
        public string? fileUrl { get; set; }

        [JsonPropertyName("downloadFailed")]
        public bool? downloadFailed { get; set; }

        [JsonPropertyName("fileType")]
        public NamedEntityDto? fileType { get; set; }

        [JsonPropertyName("fileDataId")]
        public int? fileDataId { get; set; }

        [JsonPropertyName("ownerSystemUserId")]
        public int? ownerSystemUserId { get; set; }

        [JsonPropertyName("sourceTemplateId")]
        public int? sourceTemplateId { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public class RegionDto
    {
        [JsonPropertyName("treePathId")]
        public string? treePathId { get; set; }

        [JsonPropertyName("socr")]
        public string? socr { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }

        [JsonPropertyName("oktmo")]
        public string? oktmo { get; set; }

        [JsonPropertyName("code")]
        public string? code { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }
    }



    public class SignatureListDto
    {
        [JsonPropertyName("certificateOwner")]
        public string? certificateOwner { get; set; }

        [JsonPropertyName("signingDate")]
        public DateTimeOffset? signingDate { get; set; }

        [JsonPropertyName("certificateSystemUserId")]
        public int? certificateSystemUserId { get; set; }

        [JsonPropertyName("signatureDataFileHash")]
        public string? signatureDataFileHash { get; set; }

        [JsonPropertyName("isCurrentUser")]
        public bool? isCurrentUser { get; set; }

        [JsonPropertyName("mrpaInfo")]
        public SignatureMrpaDto? mrpaInfo { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public class SignatureMrpaDto
    {
        [JsonPropertyName("createdDate")]
        public DateTimeOffset? createdDate { get; set; }

        [JsonPropertyName("updatedDate")]
        public DateTimeOffset? updatedDate { get; set; }

        [JsonPropertyName("registrationNumber")]
        public string? registrationNumber { get; set; }

        [JsonPropertyName("issueDate")]
        public DateTimeOffset? issueDate { get; set; }

        [JsonPropertyName("expiredDate")]
        public DateTimeOffset? expiredDate { get; set; }

        [JsonPropertyName("externalNumber")]
        public string? externalNumber { get; set; }

        [JsonPropertyName("fileStorageId")]
        public int? fileStorageId { get; set; }

        [JsonPropertyName("id")]
        public string? id { get; set; }
    }



    public class SignedExternalFileDto
    {
        [JsonPropertyName("signatures")]
        public List<FileSignature>? signatures { get; set; }

        [JsonPropertyName("type")]
        public string? type { get; set; }

        [JsonPropertyName("fileUrl")]
        public string? fileUrl { get; set; }

        [JsonPropertyName("fileName")]
        public string? fileName { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public class SupplierDto2
    {
        [JsonPropertyName("url")]
        public string? url { get; set; }

        [JsonPropertyName("rate")]
        public double? rate { get; set; }

        [JsonPropertyName("bankAccounts")]
        public List<BankAccountDto>? bankAccounts { get; set; }

        [JsonPropertyName("contacts")]
        public List<ContactInfo>? contacts { get; set; }

        [JsonPropertyName("country")]
        public string? country { get; set; }

        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("ikoCode")]
        public string? ikoCode { get; set; }

        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("kpp")]
        public string? kpp { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("ogrn")]
        public string? ogrn { get; set; }

        [JsonPropertyName("okato")]
        public string? okato { get; set; }

        [JsonPropertyName("okfs")]
        public string? okfs { get; set; }

        [JsonPropertyName("okopf")]
        public string? okopf { get; set; }

        [JsonPropertyName("okpo")]
        public string? okpo { get; set; }

        [JsonPropertyName("oksm")]
        public string? oksm { get; set; }

        [JsonPropertyName("oktmo")]
        public string? oktmo { get; set; }

        [JsonPropertyName("okved")]
        public string? okved { get; set; }

        [JsonPropertyName("shortName")]
        public string? shortName { get; set; }

        [JsonPropertyName("type")]
        public CompanyTypeEnum? type { get; set; }

        [JsonPropertyName("region")]
        public RegionDto? region { get; set; }

        [JsonPropertyName("companyEntityId")]
        public int? companyEntityId { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public class CharacteristicFilterDto
    {
        [JsonPropertyName("dateRange")]
        public DateTime? dateRange { get; set; }

        [JsonPropertyName("decimalRange")]
        public Decimal? decimalRange { get; set; }

        [JsonPropertyName("id")]
        public int id { get; set; } = default!;

        [JsonPropertyName("intRange")]
        public Int324? intRange { get; set; }

        [JsonPropertyName("stringFilter")]
        public StringFilter? stringFilter { get; set; }

        [JsonPropertyName("values")]
        public List<object>? values { get; set; }
    }



    public enum AuctionStateEnum
    {
        draft,
        active,
        failed,
        finished,
        canceled,
        offersSigned,
        waitingForApprove,
    }



    public enum ContractActionObjectTypeEnum
    {
        contractProject,
        supplementaryAgreement,
        terminateAgreement,
    }



    public enum SkuCreationSourceEnum2
    {
        none,
        fromRequest,
        massYmlImport,
        externalSystemImport,
        admin,
        changeSkuOksm,
    }



    public class LogisticsOrderItemCommodityDto
    {
        [JsonPropertyName("costPerUnit")]
        public int? costPerUnit { get; set; }

        [JsonPropertyName("markingCode")]
        public string? markingCode { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("quantity")]
        public int? quantity { get; set; }

        [JsonPropertyName("vatRate")]
        public VatRateEnum? vatRate { get; set; }
    }



    public class AddresseeInfoDto
    {
        [JsonPropertyName("supplier")]
        public NamedEntityDto? supplier { get; set; }

        [JsonPropertyName("company")]
        public NamedEntityDto? company { get; set; }

        [JsonPropertyName("spUser")]
        public AddresseeInfoUserDto? spUser { get; set; }
    }



    public class AddresseeInfoUserDto
    {
        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("mail")]
        public string? mail { get; set; }

        [JsonPropertyName("login")]
        public string? login { get; set; }

        [JsonPropertyName("description")]
        public string? description { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public enum AggregateTypeEnum
    {
        day,
        week,
        month,
        threeMonths,
        year,
        allTime,
    }



    public class StatisticDto
    {
        [JsonPropertyName("date")]
        public DateTimeOffset? date { get; set; }

        [JsonPropertyName("entityId")]
        public string? entityId { get; set; }

        [JsonPropertyName("entityTypeId")]
        public string? entityTypeId { get; set; }

        [JsonPropertyName("jsonData")]
        public string? jsonData { get; set; }

        [JsonPropertyName("value")]
        public double? value { get; set; }

        [JsonPropertyName("valueTypeId")]
        public string? valueTypeId { get; set; }

        [JsonPropertyName("aggregateTypeId")]
        public AggregateTypeEnum? aggregateTypeId { get; set; }

        [JsonPropertyName("id")]
        public string? id { get; set; }
    }



    public class SupplierDto3
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<SupplierDto2>? items { get; set; }
    }



    public class ContractListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<ContractListDto2>? items { get; set; }
    }



    public class CustomerListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<CustomerListDto2>? items { get; set; }
    }



    public class OfferListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<OfferListDto2>? items { get; set; }
    }



    public class OkpdListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<OkpdListDto2>? items { get; set; }
    }



    public class ProductionDirectoryListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<ProductionDirectoryListDto2>? items { get; set; }
    }



    public class ProductionListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<ProductionListDto2>? items { get; set; }
    }



    public class ExtendSkuListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<ExtendSkuListDto2>? items { get; set; }
    }



    public class SkuListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<SkuListDto2>? items { get; set; }
    }



    public class SkuChangeRequestListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<SkuChangeRequestListDto2>? items { get; set; }
    }



    public class SupplierBlockHistoryDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<SupplierBlockHistoryDto2>? items { get; set; }
    }



    public class TenderListDto
    {
        [JsonPropertyName("count")]
        public int? count { get; set; }

        [JsonPropertyName("items")]
        public List<TenderListDto2>? items { get; set; }
    }



    public class Int32
    {
        [JsonPropertyName("ids")]
        public Int322? ids { get; set; }
    }



    public class Int322
    {
        [JsonPropertyName("isInverted")]
        public bool? isInverted { get; set; }

        [JsonPropertyName("withHierarchy")]
        public bool? withHierarchy { get; set; }

        [JsonPropertyName("isNotNull")]
        public bool? isNotNull { get; set; }

        [JsonPropertyName("isNull")]
        public bool? isNull { get; set; }

        [JsonPropertyName("values")]
        public List<int>? values { get; set; }
    }



    public class Int323
    {
        [JsonPropertyName("isInverted")]
        public bool? isInverted { get; set; }

        [JsonPropertyName("withHierarchy")]
        public bool? withHierarchy { get; set; }

        [JsonPropertyName("isNotNull")]
        public bool? isNotNull { get; set; }

        [JsonPropertyName("isNull")]
        public bool? isNull { get; set; }

        [JsonPropertyName("values")]
        public List<int>? values { get; set; }
    }



    public class String
    {
        [JsonPropertyName("isInverted")]
        public bool? isInverted { get; set; }

        [JsonPropertyName("withHierarchy")]
        public bool? withHierarchy { get; set; }

        [JsonPropertyName("isNotNull")]
        public bool? isNotNull { get; set; }

        [JsonPropertyName("isNull")]
        public bool? isNull { get; set; }

        [JsonPropertyName("values")]
        public List<string>? values { get; set; }
    }



    public class OrderDto
    {
        [JsonPropertyName("desc")]
        public bool? desc { get; set; }

        [JsonPropertyName("field")]
        public string? field { get; set; }
    }



    public class DateTime
    {
        [JsonPropertyName("end")]
        public DateTimeOffset? end { get; set; }

        [JsonPropertyName("isExclusive")]
        public bool? isExclusive { get; set; }

        [JsonPropertyName("isNotNull")]
        public bool? isNotNull { get; set; }

        [JsonPropertyName("isNull")]
        public bool? isNull { get; set; }

        [JsonPropertyName("start")]
        public DateTimeOffset? start { get; set; }

        [JsonPropertyName("useAsSingleValue")]
        public bool? useAsSingleValue { get; set; }
    }



    public class Decimal
    {
        [JsonPropertyName("end")]
        public double? end { get; set; }

        [JsonPropertyName("isExclusive")]
        public bool? isExclusive { get; set; }

        [JsonPropertyName("isNotNull")]
        public bool? isNotNull { get; set; }

        [JsonPropertyName("isNull")]
        public bool? isNull { get; set; }

        [JsonPropertyName("start")]
        public double? start { get; set; }

        [JsonPropertyName("useAsSingleValue")]
        public bool? useAsSingleValue { get; set; }
    }



    public class Int324
    {
        [JsonPropertyName("end")]
        public int? end { get; set; }

        [JsonPropertyName("isExclusive")]
        public bool? isExclusive { get; set; }

        [JsonPropertyName("isNotNull")]
        public bool? isNotNull { get; set; }

        [JsonPropertyName("isNull")]
        public bool? isNull { get; set; }

        [JsonPropertyName("start")]
        public int? start { get; set; }

        [JsonPropertyName("useAsSingleValue")]
        public bool? useAsSingleValue { get; set; }
    }



    public class StringFilter
    {
        [JsonPropertyName("isInverted")]
        public bool? isInverted { get; set; }

        [JsonPropertyName("contains")]
        public bool? contains { get; set; }

        [JsonPropertyName("startsWith")]
        public bool? startsWith { get; set; }

        [JsonPropertyName("endsWith")]
        public bool? endsWith { get; set; }

        [JsonPropertyName("isNotNull")]
        public bool? isNotNull { get; set; }

        [JsonPropertyName("isNull")]
        public bool? isNull { get; set; }

        [JsonPropertyName("value")]
        public string? value { get; set; }
    }



    public class LicenseRequestDto
    {
        [JsonPropertyName("comment")]
        public string? comment { get; set; }
    }



    public class NotificationOfInvitationDto
    {
        [JsonPropertyName("regionId")]
        public List<int>? regionId { get; set; }

        [JsonPropertyName("supplierCompanyId")]
        public List<int>? supplierCompanyId { get; set; }

        [JsonPropertyName("toAllInterested")]
        public bool? toAllInterested { get; set; }
    }



    public class SupplierFileDto
    {
        [JsonPropertyName("type")]
        public SupplierFileTypeEnum? type { get; set; }

        [JsonPropertyName("fileUrl")]
        public string? fileUrl { get; set; }

        [JsonPropertyName("fileName")]
        public string? fileName { get; set; }
    }



    public enum SupplierFileTypeEnum
    {
        license,
    }



}
