// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Zakupki.MosApi
{
    public class ContractQueryFilter
    {
        [JsonPropertyName("ids")]
        public Int322? ids { get; set; }

        [JsonPropertyName("regionIds")]
        public Int323? regionIds { get; set; }

        [JsonPropertyName("statusIds")]
        public Int323? statusIds { get; set; }

        [JsonPropertyName("customerINN")]
        public String? customerINN { get; set; }

        [JsonPropertyName("supplierINN")]
        public String? supplierINN { get; set; }

        [JsonPropertyName("createDate")]
        public DateTime? createDate { get; set; }

        [JsonPropertyName("updateDate")]
        public DateTime? updateDate { get; set; }
    }



    public class GetContractStatsQuery
    {
        [JsonPropertyName("filter")]
        public ContractQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class GetContractsQuery
    {
        [JsonPropertyName("filter")]
        public ContractQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class CustomerQueryFilter
    {
        [JsonPropertyName("ids")]
        public Int322? ids { get; set; }

        [JsonPropertyName("regionIds")]
        public Int323? regionIds { get; set; }
    }



    public class GetCustomersQuery
    {
        [JsonPropertyName("filter")]
        public CustomerQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class GetOffersQuery
    {
        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("filter")]
        public OfferFilterDto? filter { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class GetOkpdReferenceQuery
    {
        [JsonPropertyName("filter")]
        public OkpdQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class GetProductionDirectoryReferenceQuery
    {
        [JsonPropertyName("filter")]
        public ProductionDirectoryQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class GetProductionReferenceQuery
    {
        [JsonPropertyName("filter")]
        public ProductionQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class OkpdQueryFilter
    {
        [JsonPropertyName("code")]
        public StringFilter? code { get; set; }

        [JsonPropertyName("ids")]
        public Int322? ids { get; set; }

        [JsonPropertyName("parentIds")]
        public Int323? parentIds { get; set; }

        [JsonPropertyName("name")]
        public StringFilter? name { get; set; }

        [JsonPropertyName("isLastLevel")]
        public bool? isLastLevel { get; set; }
    }



    public class ProductionDirectoryQueryFilter
    {
        [JsonPropertyName("productionIds")]
        public Int323? productionIds { get; set; }

        [JsonPropertyName("entityState")]
        public int? entityState { get; set; }

        [JsonPropertyName("ids")]
        public Int322? ids { get; set; }

        [JsonPropertyName("parentIds")]
        public Int323? parentIds { get; set; }

        [JsonPropertyName("name")]
        public StringFilter? name { get; set; }

        [JsonPropertyName("isLastLevel")]
        public bool? isLastLevel { get; set; }
    }



    public class ProductionQueryFilter
    {
        [JsonPropertyName("code")]
        public StringFilter? code { get; set; }

        [JsonPropertyName("isInnovation")]
        public bool? isInnovation { get; set; }

        [JsonPropertyName("ids")]
        public Int322? ids { get; set; }

        [JsonPropertyName("parentIds")]
        public Int323? parentIds { get; set; }

        [JsonPropertyName("name")]
        public StringFilter? name { get; set; }

        [JsonPropertyName("isLastLevel")]
        public bool? isLastLevel { get; set; }
    }



    public class GetRegionsReferenceQuery
    {
    }



    public class RegionListDto
    {
        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("socr")]
        public string? socr { get; set; }

        [JsonPropertyName("code")]
        public string? code { get; set; }

        [JsonPropertyName("id")]
        public int? id { get; set; }
    }



    public class GetExternalSkusQuery
    {
        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("filter")]
        public SkuFilterDto? filter { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class GetSkuQuery
    {
        [JsonPropertyName("ids")]
        public List<int>? ids { get; set; }

        [JsonPropertyName("offerType")]
        public SkuQueryOfferTypeEnum? offerType { get; set; }
    }



    public class GetSkusQuery
    {
        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("filter")]
        public SkuFilterDto? filter { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class GetExternalSkuChangeRequestsQuery
    {
        [JsonPropertyName("filter")]
        public SkuChangeRequestQueryFilter? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class SkuChangeRequestQueryFilter
    {
        [JsonPropertyName("ids")]
        public Int322? ids { get; set; }

        [JsonPropertyName("requestTypeIds")]
        public Int323? requestTypeIds { get; set; }

        [JsonPropertyName("stateIds")]
        public Int323? stateIds { get; set; }

        [JsonPropertyName("publishDate")]
        public DateTime? publishDate { get; set; }

        [JsonPropertyName("skuIds")]
        public Int323? skuIds { get; set; }
    }



    public class GetStatisticsQuery
    {
        [JsonPropertyName("minDate")]
        public DateTimeOffset? minDate { get; set; }

        [JsonPropertyName("maxDate")]
        public DateTimeOffset? maxDate { get; set; }

        [JsonPropertyName("aggregateDate")]
        public DateTimeOffset? aggregateDate { get; set; }

        [JsonPropertyName("maxCount")]
        public int? maxCount { get; set; }

        [JsonPropertyName("entityIds")]
        public List<string>? entityIds { get; set; }

        [JsonPropertyName("entityTypeId")]
        public string? entityTypeId { get; set; }

        [JsonPropertyName("valueTypeIds")]
        public List<string>? valueTypeIds { get; set; }

        [JsonPropertyName("aggregateTypeId")]
        public AggregateTypeEnum? aggregateTypeId { get; set; }
    }



    public class GetSupplierBlockHistoryQuery
    {
        [JsonPropertyName("filter")]
        public Int32? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class GetSuppliersByIdsQuery
    {
        [JsonPropertyName("ids")]
        public List<int>? ids { get; set; }
    }



    public class GetSuppliersQuery
    {
        [JsonPropertyName("filter")]
        public SupplierFilterDto? filter { get; set; }

        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class SupplierFilterDto
    {
        [JsonPropertyName("ids")]
        public Int322? ids { get; set; }

        [JsonPropertyName("regionIds")]
        public Int322? regionIds { get; set; }

        [JsonPropertyName("isBlocked")]
        public bool? isBlocked { get; set; }

        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("kpp")]
        public string? kpp { get; set; }

        [JsonPropertyName("blockDate")]
        public DateTime? blockDate { get; set; }
    }



    public class GetTendersQuery
    {
        [JsonPropertyName("order")]
        public List<OrderDto>? order { get; set; }

        [JsonPropertyName("filter")]
        public TenderFilterDto? filter { get; set; }

        [JsonPropertyName("doNotOrder")]
        public bool? doNotOrder { get; set; }

        [JsonPropertyName("skip")]
        public int? skip { get; set; }

        [JsonPropertyName("take")]
        public int? take { get; set; }

        [JsonPropertyName("withCount")]
        public bool? withCount { get; set; }

        [JsonPropertyName("onlyCount")]
        public bool? onlyCount { get; set; }
    }



    public class SkuLimitedPriceDto
    {
        [JsonPropertyName("price")]
        public double? price { get; set; }

        [JsonPropertyName("dueDate")]
        public DateTimeOffset? dueDate { get; set; }

        [JsonPropertyName("contractId")]
        public int? contractId { get; set; }

        [JsonPropertyName("auctionId")]
        public int? auctionId { get; set; }

        [JsonPropertyName("offerId")]
        public int? offerId { get; set; }
    }



    public class AddExternalIntegrationQueueCommand
    {
        [JsonPropertyName("body")]
        public string? body { get; set; }

        [JsonPropertyName("externalSystemUserId")]
        public int externalSystemUserId { get; set; } = default!;

        [JsonPropertyName("packageType")]
        public string? packageType { get; set; }

        [JsonPropertyName("systemUserId")]
        public int? systemUserId { get; set; }

        [JsonPropertyName("diagnosticsActivityId")]
        public string? diagnosticsActivityId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }



    public class OperationCompleteCommand
    {
        [JsonPropertyName("hasErrors")]
        public bool? hasErrors { get; set; }

        [JsonPropertyName("errors")]
        public Dictionary<string, object>? errors { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }



    public class OperationCompleteCommand2
    {
        [JsonPropertyName("hasErrors")]
        public bool? hasErrors { get; set; }

        [JsonPropertyName("errors")]
        public Dictionary<string, object>? errors { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }



    public class ProcessIntegrationQueueCommand
    {
        [JsonPropertyName("packageId")]
        public string? packageId { get; set; }

        [JsonPropertyName("operationId")]
        public string? operationId { get; set; }

        [JsonPropertyName("jsonServiceInfo")]
        public string? jsonServiceInfo { get; set; }
    }



    public enum LogisticServiceEnum
    {
        dellin,
        sberLogistics,
        yandexGo,
    }



    public class CompanyDto
    {
        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("shortName")]
        public string? shortName { get; set; }

        [JsonPropertyName("inn")]
        public string? inn { get; set; }

        [JsonPropertyName("isJuridical")]
        public bool? isJuridical { get; set; }

        [JsonPropertyName("opfName")]
        public string? opfName { get; set; }
    }



    public enum LogisticsDeliveryTypeEnum
    {
        dellinAuto,
        dellinExpress,
        dellinLetter,
        dellinAvia,
        dellinSmall,
        sbeR_COURIER,
        sbeR_COURIER_EXPRESS,
        sbeR_COURIER_ECONOMY_CARGO,
    }



    public class LogisticsOrderDto
    {
        [JsonPropertyName("id")]
        public string? id { get; set; }

        [JsonPropertyName("logisticsProvider")]
        public LogisticServiceEnum? logisticsProvider { get; set; }

        [JsonPropertyName("deliveryType")]
        public LogisticsDeliveryTypeEnum? deliveryType { get; set; }

        [JsonPropertyName("externalId")]
        public string? externalId { get; set; }

        [JsonPropertyName("externalState")]
        public NamedEntityDto? externalState { get; set; }

        [JsonPropertyName("fromCompany")]
        public CompanyDto? fromCompany { get; set; }

        [JsonPropertyName("toCompany")]
        public CompanyDto? toCompany { get; set; }

        [JsonPropertyName("fromAddress")]
        public FiasAddressDto? fromAddress { get; set; }

        [JsonPropertyName("toAddress")]
        public FiasAddressDto? toAddress { get; set; }

        [JsonPropertyName("derivalProduceDate")]
        public DateTimeOffset? derivalProduceDate { get; set; }

        [JsonPropertyName("totalCost")]
        public double? totalCost { get; set; }

        [JsonPropertyName("minDeliveryDate")]
        public DateTimeOffset? minDeliveryDate { get; set; }

        [JsonPropertyName("maxDeliveryDate")]
        public DateTimeOffset? maxDeliveryDate { get; set; }

        [JsonPropertyName("calculatedTotalCost")]
        public double? calculatedTotalCost { get; set; }

        [JsonPropertyName("calculatedMinDeliveryDate")]
        public DateTimeOffset? calculatedMinDeliveryDate { get; set; }

        [JsonPropertyName("calculatedMaxDeliveryDate")]
        public DateTimeOffset? calculatedMaxDeliveryDate { get; set; }

        [JsonPropertyName("items")]
        public List<LogisticsOrderItemDto>? items { get; set; }

        [JsonPropertyName("freightName")]
        public string? freightName { get; set; }

        [JsonPropertyName("paymentByCash")]
        public bool? paymentByCash { get; set; }

        [JsonPropertyName("senderContactPerson")]
        public string? senderContactPerson { get; set; }

        [JsonPropertyName("senderPhone")]
        public string? senderPhone { get; set; }

        [JsonPropertyName("senderEmail")]
        public string? senderEmail { get; set; }

        [JsonPropertyName("senderDocumentNumber")]
        public string? senderDocumentNumber { get; set; }

        [JsonPropertyName("senderWorkTime")]
        public DateTimeRangeDto? senderWorkTime { get; set; }

        [JsonPropertyName("receiverContactPerson")]
        public string? receiverContactPerson { get; set; }

        [JsonPropertyName("receiverPhone")]
        public string? receiverPhone { get; set; }

        [JsonPropertyName("receiverDocumentNumber")]
        public string? receiverDocumentNumber { get; set; }

        [JsonPropertyName("receiverWorkTime")]
        public DateTimeRangeDto? receiverWorkTime { get; set; }

        [JsonPropertyName("comment")]
        public string? comment { get; set; }

        [JsonPropertyName("cashOnDelivery")]
        public int? cashOnDelivery { get; set; }

        [JsonPropertyName("insuranceSum")]
        public int? insuranceSum { get; set; }

        [JsonPropertyName("contractNumber")]
        public string? contractNumber { get; set; }

        [JsonPropertyName("individualTariff")]
        public string? individualTariff { get; set; }

        [JsonPropertyName("orderNumber")]
        public string? orderNumber { get; set; }

        [JsonPropertyName("errorMessages")]
        public List<string>? errorMessages { get; set; }
    }



    public class LogisticsOrderItemDto
    {
        [JsonPropertyName("name")]
        public string? name { get; set; }

        [JsonPropertyName("quantity")]
        public int? quantity { get; set; }

        [JsonPropertyName("weight")]
        public double? weight { get; set; }

        [JsonPropertyName("length")]
        public double? length { get; set; }

        [JsonPropertyName("width")]
        public double? width { get; set; }

        [JsonPropertyName("height")]
        public double? height { get; set; }

        [JsonPropertyName("commodities")]
        public List<LogisticsOrderItemCommodityDto>? commodities { get; set; }
    }



    public class LogisticsOrderDto2
    {
        [JsonPropertyName("correlationId")]
        public string? correlationId { get; set; }

        [JsonPropertyName("orderData")]
        public LogisticsOrderDto? orderData { get; set; }
    }



    public class Void
    {
    }
}
